### ISSUE TITLE
repeat.for items evaluated multiple times

### ISSUE THREAD

**Issue by MercinaM** [aurelia/aurelia#1118]
I've noticed a weird behaviour with repeaters when debugging one of our apps - some of the items in a repeater were calling a render method twice per item, despite the fact that the underlying data never changed. I noticed the problem go away when I deleted part of the template, and it did not matter which part of the template I deleted, only that I deleted some of it.

To simulate the issue I've created the following example: [https://codepen.io/Haltesh/project/editor/Xkxozd](https://codepen.io/Haltesh/project/editor/Xkxozd)

app.html: 
```
<template>
  <span repeat.for="i of 97">${i} </span>
  <ul>
    <li repeat.for="item of items">
      ${renderItem(item)}
    </li>
  </ul>
  <button type="button" click.delegate="reset()">reset</button>
</template>
```
app.js:
```
export class App {
  constructor() {
    this.reset();
  }
  
  renderItem(item) {
    console.log(item.title);
    
    this.renderCount++;
    
    return this.renderCount.toString() + ": " + item.title;
  }
  
  reset() {
    this.renderCount = 0;
    this.items = [
      { title: "First" },
      { title: "Second" },
      { title: "Third" },
      { title: "Fourth" }
    ];
  }
}
```
The renderTodo method uses a counter to make it easier to spot the issue in the HTML output, but the issue is the same if I remove the counter and just rely on the console output.

I used two repeaters to make it easier to change the number of bindings for the app, but the behavior is the same if I replace the first repeater with the same number of static bindings (i.e. ${'1'} ${'2'} ${'3'} ...  ${'97'}).

If I have up to 94 bindings in the first repeater, each item in the second repeater will be evaluated exactly once, which is the expected behavior:

![image](https://user-images.githubusercontent.com/12325231/108328658-25b84600-71cd-11eb-8470-c26dfa6c39a4.png)

If I increase the number of bindings by 1, to 95, the first three items are evaluated once, but the last item is evaluated twice:

![image](https://user-images.githubusercontent.com/12325231/108328334-c4907280-71cc-11eb-8811-0ab014f8f22e.png)

From this point on, whenever I increase the number of bindings by 1, one more item (in order from last to first) will exhibit the issue, which means at 98 every single item will be evaluated twice:

![image](https://user-images.githubusercontent.com/12325231/108330594-0ec62380-71ce-11eb-9a3c-0a6bf37007d4.png)

After that the behavior does not change, whether I use 98 or 10000 bindings in the first repeater, each item will be evaluated exactly twice.

Another point of interest is that the issue only appears to present itself on the initial render. If I swap out the repeater data for an identical set using the "reset" button, forcing a re-render, each item is evaluated only once.

**Comment by bigopon** [comment]
Thank you for the issue. This is a v1 related q, and a demo of the above pen for anyone intertest is at https://gist.dumber.app/?gist=721a4100120c7d9bfe69fc3485b5e45e

This behavior is related to the task queue in binding, and how everything in v1 works around it. As you can see from the demo, disabling the connect queue makes it render only once for the last item. It can be explained as:
- the queue capacity is 100 items. if anything during initial `bind` phase exceeds 100, it will be called next turn
- when there' 95 items in the first repeat, the last item of the 2nd repeat is evaluated twice: 1 call for initial `binding.bind()` call -> queued for connect & 1 call for for re-evaluating.

This is the expected behavior. If this is causing issue to your app, maybe try make `render` method idempotent? Or you can also disable the queue, or increase it capacity.

**Comment by MercinaM** [comment]
Thank you very much for your response.

The behavior was not causing any issued in our app, but it did make me slightly worried about potential performance implications should the items array become too large.

Having a better idea of how exactly it works helps put my mind at ease, and seeing as this is the expected behavior I am closing the issue.
