### ISSUE TITLE
Aurelia 2 does not work with file names index.html/index.ts and unnamed classes

### ISSUE THREAD

**Issue by hoangcuongvn** [aurelia/aurelia#1374]
# 🐛 Bug Report
In Aurelia 1, I can use file names `index.html/index.ts` for custom elements and routes. E.g
```
resources
  custom-elements
    my-element
      index.html
      index.ts
routes
  my-route
    index.html
    index.ts
```
But in Aurelia 2, the app crashes if I use file names `index.html/index.ts` (as in the file structure above) for custom elements and routes. It's strange that Aurelia 2 accepts any file names e.g `foo.html/foo.ts` but `index.html/index.ts`.

In Aurelia 1, I can use unnamed for route classes. E.g
```
// routes/my-route.ts
export default class {
}
```
Aurelia 2 does not accept the unnamed class above even through the route configuration does not require a class name. E.g
```
@route({
  routes: [
    {
      path: "my-path",
      component: import("routes/my-route"),
    },
  ]
})
```
I think Aurelia 2 should support unnamed classes as in Aurelia 1.
## 🌍 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | Latest
| Language         | Typescript
| Browser          | Chrome/Firefox
| Bundler          | Webpack
| Operating System | Win10
| NPM/Node/Yarn    | NPM 1.17.0, Node 16.3.0, Yarn 1.22.15

**Comment by 3cp** [comment]
I did use `index.js` for router component in Aurelia v1.
Aurelia v1 figures out every details at runtime, while Aurelia 2 does it in compile time with static analysis. In other words, Aurelia 2 tooling modifies your source code.

For Aurelia v1, as long as the module loading works, it can get the element. For example `<require from="./my-element"></require>` will try `my-element.js/ts`, and fallback to `my-element/index.js/ts` (this is part of Nodejs module resolution).

For Aurelia 2, right now, we assign custom-element name at compile name based on file name. So it will assign name "index" to the element `@customElement({name: 'index',` for that `index.js` file. We could update the logic to decide custom-element name based on the whole file path, not just the file name.

As for router component, the story is little bit different. Aurelia v1 router does NOT case about the custom-element name (because it didn't need to use the name). As long as you have only one export in the component, no matter what name you gave, Aurelia v1 will just load that component. The default export is almost same as a named "default" export (although strictly it should be default export from a namespace, it actually is a "default" property on an object due to transpiling.)

However, Aurelia 2 requires you put perfect name on the export because it needs the tooling to add `@customElement` decorator. The tooling modifies user code very defensively, we don't want to modify user code unless we are very sure. But in compile time, it's too hard to figure out whether this file is used as a router component or just a normal custom element.

So if we decided to add `foo/index.js` support in our tooling, we still require user to name export properly. This is due to the nature of static analysis at compile time, we don't want to make too many assumptions which will dangerously leads to more edge cases.

(I do miss the dynamic nature of Aurelia v1, it enables tons of flexible use cases.)

**Comment by 3cp** [comment]
To be tested after next alpha release.

**Comment by bigopon** [comment]
@hoangcuongvn the feature has been released in alpha 27, can you give it a try?

**Comment by hoangcuongvn** [comment]
@bigopon I just upgraded the latest version (alpha 27) and I saw `index.html/index.ts` now work properly.

**Comment by bigopon** [comment]
@hoangcuongvn thanks 👍
