### ISSUE TITLE
The containerless decorator has no effect after alpha v29

### ISSUE THREAD

**Issue by bsrdjan** [aurelia/aurelia#1474]
The `containerless()` decorator has no effect after alpha v29 and still works in v29.

**Comment by Sayan751** [comment]
@bsrdjan Are you using this with the conventions? Or are you explicitly using the `@cutomElement` decorator? If it is the latter, then you can simply set the `containerless` property in the decorator option.

In case you are using both `@cutomElement` and `@containerless` decorators, ensure to apply the `@cutomElement` decorator on top of `@containerless` decorator, and not the other way around. A correct usage will be as follows:

```typescript

// @containerless() // <-- this won't work

@customElement({
  name: 'ce-foo',
  template: 'ce-foo'
})
@containerless()
export class CeFoo { }
```

This is an artefact of the order of execution of the decorators. The `@containerless()` decorator must mark (store the relevant metadata) the CE as containerless first, which is later utilized by the `@customElement`. And that's why the order is important.

**Comment by bsrdjan** [comment]
I am using `containerless()` decorator with conventions, on regular page, like welcome page from au2 bootstrap app. It works in au1 and worked in au2 v29

Best regards / Viele Grüße,

Srdjan

~ sent from handheld ~
________________________________
