### ISSUE TITLE
Ability to spread an object to bindables

### ISSUE THREAD

**Issue by brandonseydel** [aurelia/aurelia#1477]
# 🙋 Feature Request

When looping through sometimes I would like to spread the object I am looping through on the component rather than oen by one

## 🤔 Expected Behavior

```ts
        <k-button  repeat.for="action of actions" ...action>${action.content}</k-button>
```

## 😯 Current Behavior

```ts
        <k-button color.bind="action.color"
                          size.bind="action.size"
                          type.bind="action.type" 
                          epeat.for="action of actions">${action.content}</k-button>

```

## 💁 Possible Solution

Allow some form of spread to bind al properties from object that match

**Comment by Vheissu** [comment]
Yes, please. Most of my Aurelia applications are littered with redundant bind statements mapping to property names in objects.

**Comment by bigopon** [comment]
One question we haven't answered since the first efforts long ago is what happens when a new property is added. If we are to ignore, this feature is easy to implement but there will be mis-expectation. If we are to subscribe & notify, we don't have a way to subscribe in a proper way:

Says there's a custom element `el` with bindables `value`, and we have this templae
```html
<let object.bind="{ value: 1, id: 'hello' }"></let>
<el ...object></el>
```
Where should the properties in the `object` go? Should both `value` and `id` go to the view model, or the host element? or should `value` go to the view model while `id` goes to the host element?

**Comment by brandonseydel** [comment]
@bigopon - only bindables unless there is a @bindable({type:Object}) maybe?

**Comment by brandonseydel** [comment]
@bigopon - I was only thinking the spread to work on CE not native elements as well (for first phase)

**Comment by bigopon** [comment]
> @bigopon - I was only thinking the spread to work on CE not native elements as well (for first phase)

If we are to do this, we can also do spreading based on host: if a CE host then spread into the view model, and if not, spread into the host element.
It'll solve some of the ergonomic issues. Though it won't solve the mis-expectation with the added properties, at least yet.
