### ISSUE TITLE
switch/case not working when combined with if attribute

### ISSUE THREAD

**Issue by elitastic** [aurelia/aurelia#1646]
# 🐛 Bug Report

`switch/case` attribute is not working when combined with `if` attribute. There's a console error:

`The parent switch not found; only "*[switch] > *[case|default-case]" relation is supported.`

See repro: https://stackblitz.com/edit/au2-conventions-dkph9q

## 🤔 Expected Behavior

`if.bind` should remove switch/case element from dom.

## 😯 Current Behavior

`if.bind` does not remove switch/case element from dom.

## 💻 Code Sample

https://stackblitz.com/edit/au2-conventions-dkph9q

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | dev
| Browser          | Brave
| Bundler          | Webpack 5
| Operating System | Windows
| NPM/Node/Yarn    | 7.17.0

**Comment by Sayan751** [comment]
You need to reorder the `if` and `switch`. Here is a working example: https://stackblitz.com/edit/au2-conventions-zjhzbq?file=src/my-app.html

```diff
- <div switch.bind="prop" if.bind="isEnabled">
+ <div if.bind="isEnabled" switch.bind="prop">
```

When you are `<div switch.bind="prop" if.bind="isEnabled">`, it can be roughly thought as 

```html
<div switch.bind="prop">
  <template if.bind="isEnabled">
    <!-- here comes the cases -->
  </template>
</div>
```

And clearly this nesting is semantically invalid. 

I am closing this. Feel free to continue the discussion.

**Comment by elitastic** [comment]
Thanks for your help. Your explanation makes sense. However, I wonder if this could not be solved by the framework itself, for example by prioritizing some attributes or something similar.

**Comment by bigopon** [comment]
This can be theoretically solved with AOT. for JIT, we probably won't even attempt, because it's harder to preserve WYSIWYG with JIT, also, it's hard.

**Comment by elitastic** [comment]
@bigopon @Sayan751  Many thanks for your reply. Should we consider reopening this issue?

**Comment by Sayan751** [comment]
@elitastic To be honest, I am not inclined towards having this implemented. There are a couple of reasons for that.

1. The current behaviour is in sync with JS. When you write a `switch` in JS, you don't expect an `if` directly nested under the `switch` to work. The current behaviour mirror that. Otherwise, I would find the syntax to be a bit confusing.
2. We cannot simply introduce a "rule" that reorders the `switch` and `if`. Because that will with high probability trigger a scope creep, which we want to avoid.
3. Lastly, I personally see it as a documentation issue. When I added `switch` to Au2, I documented about these limitations. Unfortunately, the docs got misplaced during the restructuring. However, I can restore the docs that details on such issues.

However, can you please elaborate your use case where this change in behaviour is necessary?

**Comment by elitastic** [comment]
@Sayan751 I can provide you a simplified example of our code base:

```
<div if.bind="productType.numberOfProducts.length > 0"
        switch.bind="productType.key">
    <span case="A">Name of product type A</span>
    <span case="B">Name of product type B</span>
    <span default-case>Unknown</span>
</div>
```

In the meantime, I reordered all `if` and `switch` expressions in our Aurelia 1 codebase so it shouldn't be a problem anymore when we will upgrade to Aurelia 2 some day.

**Comment by Sayan751** [comment]
Thank you @elitastic for sharing the example. 

However, I am not sure that it highlights the necessity of implementing the proposed change.

>  I continue to find it somewhat surprising that attribute order matters.

Note that these attributes are a bit special, as these are template controllers. The ones out-of-the-box mimics some JS constructs, such as if-else, loop (repeat.for), switch, promise etc. If I see it correctly, then it perfectly makes sense that the JS behaviours are also mimicked, as pointed out in the first point in my [earlier comment](https://github.com/aurelia/aurelia/issues/1646#issuecomment-1435666486).

> When you write a switch in JS, you don't expect an if directly nested under the switch to work.
