### ISSUE TITLE
inject parent component within au-slot not working correctly

### ISSUE THREAD

**Issue by elitastic** [aurelia/aurelia#1683]
# 🐛 Bug Report

Parent component cannot be injected in child component when within a au-slot:

https://stackblitz.com/edit/au2-conventions-fwjxjv?file=src/a-component/child.html

## 🤔 Expected Behavior

Current instance of parent component should be injected

## 😯 Current Behavior

A new (empty) instance of the parent component is injected

## 💻 Code Sample

https://stackblitz.com/edit/au2-conventions-fwjxjv?file=src/a-component/child.html

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          | dev
| Language         | german
| Browser          | chrome
| Bundler          | webpack
| Operating System | windows
| NPM/Node/Yarn    | stackblitz

**Comment by bigopon** [comment]
This is because the container used to create slot content is not the `<child/>` container of the `<parent/>` component. We won't simply change to this, because the internal of the `<parent>` will be then available/exposed to the slotted content, which is not good. What we can do is to add an extra registration of parent component on the child component container when instantiating the slot content.

**Comment by elitastic** [comment]
Thank you @bigopon!
