### ISSUE TITLE
Dev: upgrade TS to v5.0

### ISSUE THREAD

**Issue by bigopon** [aurelia/aurelia#1711]
This should help with build time local & CI time, also allow us to start migrating to the new decorator feature of the language.

**Comment by Vheissu** [comment]
Firstly, @bigopon, incredible write-up. Loved the examples of other frameworks/libs and explanation of the state-tearing problem.

From my perspective, the sync binding mode is a bit problematic, but once you know about it, it's easy to work around using something like `batch` to address the issue. Preempting this RFC and discussion was the example I posted in the team chat around being caught out by this. Still, other people I work with were also caught out by this because we're going from Aurelia 1 to Aurelia 2. It's an easy trap to fall into, assuming things like the binding system and how things update are the same.

Understandably, concessions had to be made, and we wanted to avoid some of the issues we had with Aurelia 1.

Right now, I think this is more of a documentation/awareness issue than a fundamental problem with Aurelia 2 itself. I don't want us to delay the release of candidates because of this. Fundamentally, there is nothing major here that needs to be fixed immediately. If synchronous binding updates were causing other issues, I would be more inclined to say we should bite the bullet and look into supporting async.

Not wanting to speak for everyone here, I think what we should do in the interim is:

- Update the docs to highlight this behaviour and be very explicit in the way it works and leveraging `batch` to work around this difference compared to v1
- Write a blog post about this (which will be helpful if someone skips the docs and goes to Google instead)

I am not married to any particular approach here. I am used to the Aurelia 1 way of updating because I have worked with it for as long as others I know. It was acknowledged in v1 that if you had issues around bindings, you would throw `queueMicroTask` in your code, and the problem was solved.

In the long term, we could always cut another major release if we decide to change it. We aren't stuck with these decisions. But I do think it's more destructive in the short term to delay a stable Aurelia 2 release because this is holding up wider adoption from other libraries and tooling (like official Storybook support, etc.).

My concerns and questions here relate to performance. Is the nature of sync that things are more predictable, or does one approach provide performance benefits over the other? Because I would support whatever approach results in better performance and fewer side effects over an approach that has the potential to slow my app down as the number of bindings increases.
