### ISSUE TITLE
Plugins with HTML imports break in the default Aurelia makes skeleton

### ISSUE THREAD

**Issue by Vheissu** [aurelia/aurelia#1777]
# 🐛 Bug Report

I have been working on porting over https://github.com/aurelia-ui-toolkits/aurelia-mdc-web to Aurelia 2. Porting aside, when I attempt to consume the v2 version of the plugin in the default `npx makes aurelia` skeleton with Webpack, it complains about various `.html` files being imported not having a loader.

To fix this, I had to modify the default HTML loader and remove the exclusion rule for node modules:

```
        {
          test: /\.html$/i,
          use: '@aurelia/webpack-loader'
        },
```

You can replicate this issue by installing `@aurelia2-mdc-web/all` in a fresh Aurelia 2 project using `makes` and pulling in some of the packages

```
import { BaseConfiguration } from "@aurelia2-mdc-web/base";
import { ButtonConfiguration } from "@aurelia2-mdc-web/button";
import { CheckboxConfiguration } from "@aurelia2-mdc-web/checkbox";
import { ChipsConfiguration } from "@aurelia2-mdc-web/chips";
import { CircularProgressConfiguration } from "@aurelia2-mdc-web/circular-progress";
import { DialogConfiguration } from "@aurelia2-mdc-web/dialog";

Aurelia.register(
  BaseConfiguration,
  ButtonConfiguration,
  CheckboxConfiguration,
  ChipsConfiguration,
  CircularProgressConfiguration,
  DialogConfiguration,
)
  .app(MyApp)
  .start();

```

**Comment by Sayan751** [comment]
cc: @3cp

**Comment by 3cp** [comment]
If you start an Aurelia 2 plugin project, the html files will be compiled by `@aurelia/webpack-loader` into js code during `npm run build`.

The final npm package contains no original html file. Hence when you consume this new plugin package in an app project, there is no `.html` issue anymore because all the plugin package exposes is one dist js file.

This is different from Aurelia 1 which deal with html at runtime, not compile time. So html file retains as html file in Aurelia 1 plugin package. This is not the case anymore for Aurelia 2 plugin.

So setup Aurelia 2 plugin project properly, the html files will be handled in build time.

**Comment by bigopon** [comment]
It seems we don't need this ticket, as the original usage of `npx makes Aurelia` wasn't right, as it was for app instead of plugin. Let's close this @Vheissu ?
