### ISSUE TITLE
@aurelia/ts-jest should be upgraded to support Jest v29 to support TypeScript 5

### ISSUE THREAD

**Issue by tareqimbasher** [aurelia/aurelia#1810]
# 🙋 Feature Request

Using @aurelia/ts-jest to write Jest tests while using TypeScript >= 5 results in a warning similar to this:

```
ts-jest[versions] (WARN) Version 5.1.6 of typescript installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=4.3.0 <5.0.0-0). Please do not report issues in ts-jest if you are using unsupported versions.
```

This is because @aurelia/ts-jest is still using v28 of ts-jest. Tests still run just fine, but you still get the warning.

## 🤔 Expected Behavior

Newer versions of @aurelia/ts-jest should support TypeScript 5.

## 😯 Current Behavior

Using @aurelia/ts-jest with TypeScript 5 results in a warning. Tests still run though.

**Comment by Sayan751** [comment]
@tareqimbasher The latest versions already uses TS v5.2.2. Do you still have this issue? If so, would you be interested in submitting a PR?

cc: @3cp

**Comment by 3cp** [comment]
Every time jest upgrades major version, we have to upgrade our package too. There is no other way, since major version means possible breaking change.

https://github.com/aurelia/aurelia/blob/master/packages-tooling/ts-jest/package.json

The days that a major version can last a decade were long gone. Google Chrome started the trend to breed major versions like weed.
