### ISSUE TITLE
router-lite: null/undefined in optional parameters

### ISSUE THREAD

**Issue by elitastic** [aurelia/aurelia#1855]
# 🐛 Bug Report

Repro link https://stackblitz.com/edit/au2-conventions-nsmdrz?file=src%2Fmy-app.html

## 🤔 Expected Behavior

When passing null/undefined as optional parameters like:

`<a load="route: test; params.bind: { id: null }">Go to</a>`

I would expected the param to be `null` instead of `'null'`

## 😯 Current Behavior

null/undefined values in optional parameters are converted to "null"/"undefined"

## 🌍 Your Environment

Latest Aurelia 2 dev version

**Comment by Sayan751** [comment]
Hi @elitastic! Thanks for reporting this. If I am not wrong, then this is the same as the Aurelia 1 router. That is, the value of the parameters are converted to string regardless of types.

I think that rather than ignoring the `null` and `undefined` from this rule, we can simply leave the other type of values such as `number` and `boolean` as they are. Any other kinds of parameters values will be continued to be processed, as it is currently being done.

@bigopon What do you think about that?

**Comment by bigopon** [comment]
No objection, it does indeed feel not getting what we see. For apps migrating from v1, maybe we can explain this isn't a nice behavior so it's changed. But what happens when params come from the url?

**Comment by Sayan751** [comment]
In that case, it will remain as string. We can improve that when https://github.com/aurelia/aurelia/issues/1734 is implemented.

**Comment by elitastic** [comment]
In Aurelia 1, optional null/undefined parameters are ignored, that's why it results in `undefined`, which is way more useful than `'undefined'` in my optinion.

**Comment by Sayan751** [comment]
By optional parameter, I have understood something like this: `route/:param?`. However, by optional parameters you meant the parameters not defined for route, and thus putting into the query. Note that as for handling the query, the [`URLSearchParams` API](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) is used, and it is not supported to preserve the type of the values, and everything is converted to string.

I do understand, that you are only looking for the absence of such parameters in the query, when the value is null or undefined. I found that to be loss of data. @bigopon I am a bit torn on this issue.
