### ISSUE TITLE
[🐛] Calling store.dispatch in sequence will only set the new state once

### ISSUE THREAD

**Issue by gtroxler** [aurelia/aurelia#1871]
When store.dispatch is queuing multiple dispatch requests it seems that only the first dispatch requests results in setting the new value. Then afterDispatch is called for the each of the queued dispatch events which seems never to call _setState.

How to reproduce, build a page which dispatches multiple actions which call a rest api, subscribe to state changes and observe that only the first one will published.

Assumption every store.dispatch call that changes the state will be published to subscribers.

Code in question: https://github.com/aurelia/aurelia/blob/master/packages/state/src/store.ts
Function: dispatch

**Comment by bigopon** [comment]
This is actually a bug in `afterDispatch` and the bug is as you where you located in the PR at #1872 .
I'll be having a PR for this. Thanks for reporting.

The current behavior ignores the last `dispatch` call, which means if you have 2 dispatch call, and the handlers only return promise, it will give a feeling like the store only ever call `setState` once. You can validate this by calling dispatch 3 times, `setState` will be called twice instead.
