### ISSUE TITLE
Error Codes

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/aurelia#192]
For vNext, we'd like to have an *amazing* story around error messages. This involves:

* Verbose messages with guidance to help developers resolve the problem.
* Error codes that are easy to search and lookup in documentation.
* Error code ranges to classify and organize codes (inspired by HTTP codes).

**Comment by EisenbergEffect** [comment]
From @fkleuver:

...we should probably discuss this in a separate issue, but overall I think we should at least have the equivalents of:

1xx/2xx for verbose logging (can be a single group)
4xx invalid user input like invalid DI key, nonexisting route, missing properties
5xx deep binding/templating errors such as undefined/null references that should be guarded

**Comment by fkleuver** [comment]
Just some thoughts:

- Compile-time errors: AOT cannot compile/process, problem must be fixed by user
- Compile-time warnings: AOT can compile/process, but detected something that could cause runtime errors
- Compile-time tracing: detailed insights in the AOT resolve/transform/emit phases
- Runtime errors: violations of preconditions; invocations that are always invalid regardless of app state, such as passing `null` or `undefined` to `container.get()`, omitting the `name` property to various decorators, etc. These are detected and thrown by validation functions.
- Runtime errors: violations of invariants: same as preconditions, but these things are not checked/validated beforehand for performance reasons, usually things that "drop down" in an unhandled state such as invalid target/source context in binding, unresolvable observables, etc
- Runtime warnings: based on user configuration, certain things may warn (or even throw) where they would not by default do so, such as a warning when dirty checking is used somewhere.
- Runtime tracing: detailed logging of compiler / parser / DI / renderer flow by (probably AOT-injected) entry and exit logging methods on functions
- Unhandled exceptions: exceptions thrown by user code during lifecycles (either via rejected promises or synchronously) that bubble up to the framework code

**Comment by timfish** [comment]
+1 for error codes. TypeScript does this which makes searching for help much easier. It also helped them do things like analyse which codes were searched for most and selectively improve the error messages to help guide users.

**Comment by bigopon** [comment]
This is now resolved by #1226 The actual work of producing error code should be tracked else where.
Doc: https://docs.aurelia.io/reference/distributable
Error references https://docs.aurelia.io/reference/error-messages
