### ISSUE TITLE
Path-less Route Configs [RFC]

### ISSUE THREAD

**Issue by davismj** [aurelia/aurelia#323]
# 💬 RFC

This RFC proposes to modify the purpose of routers and routes to make the url path portion optional. This is an extension to the `IRouteConfig` section of #164 based on feedback from Discord and from ideas in #307.

## 🔦 Context

Typically, the router maps a path in the browser url bar to a particular configuration of components on the page. However, this is a specific and common case of a more general use case. 

A route serves at least one of two purposes. To associate an action with (1) a path in the browser URL (*linkability*), and (2) a entry in the navigation history (*navigability*). Typically, the action is to compose a component in a viewport, however, as discussed in #322 this is not the only supported case.

The problem with #164 is that it assumes (1) and (2) are true for all routes. This proposal serves to make (1) optional. Note that (2) is programatically optional via `router.replace()`. A future spec will propose making (2) configurably optional.

## Definition

`IRouteConfig`

The old spec required path. The new spec makes path optional.

```typescript
interface IRouteConfig {
  path?: string | string[],
}
```

### Route Configuration

```typescript
@route({
  name: 'foo'
});
export class FooRoute { }
```

### Navigation

```typescript
router.push({ name: 'foo' });
```

### Expected Result

The router will 
- load the `FooRoute` component into the default viewport with 
- a new history entry
- without any modification to the browser url.
- Should the user click the back button or otherwise navigate backward after navigating away from this page, they will be brought back to this page. 
- Should the user refresh the browser on this page, they will land on the page associated with the current URL, which should be the most recent *linkable* route in their history.

**Comment by jwx** [comment]
> * a new history entry
> * without any modification to the browser url.
> * Should the user click the back button or otherwise navigate backward after navigating away from this page, they will be brought back to this page.
> * Should the user refresh the browser on this page, they will land on the page associated with the current URL, which should be the most recent _linkable_ route in their history.

The above is interesting. What's the reason for keeping the content and url out of sync? If `bar` pushes to content `foo`, content `foo` will be displayed but url `bar` will still be shown? And refresh will restore previous content `bar` (basically behaving the same way as `back`)? And wouldn't that mean that `back` followed by `forward` would show `bar` twice? (Or rather, nothing would happen when you did `forward` because the url doesn't change.) Am I misunderstanding something here or is there a use case I've missed?

**Comment by davismj** [comment]
Content and url aren't tightly coupled. Url is one way to load content. Out of sync doesn't apply, then.

The use case is, for example, displaying a dialog, modal, or wizard. Perhaps you have a modal with 3 distinct steps. You want to use navigation to move between them. You want the browser back and forward to navigate around them. But no one should ever land on modal page 2. 

In any case, this generalization is a super set of existing specs and use cases. Opening up new options without restricting the common and most important ones in any way.

**Comment by jwx** [comment]
Sorry, what I meant was _history_ and url. And I'm in no way saying that history or content is tightly coupled with url. At least I didn't want to say that. Perhaps I did by poor choice of words. Can I play the non-native English card? 😛 

Thanks for the use cases. Now I know what you were aiming for. I've got a somewhat different solution for them, but I that they, and other "new" uses cases, are something we should aim to support.

**Comment by fkleuver** [comment]
I gave it some thought, here's what came to mind (it's not about the names of stuff in particular, but about the concepts):
- Create a `IHistory` interface that exposes roughly the same API as browser history but is not tightly coupled to the browser implementation of it
- Register `IHistory` like a resource, such that it has a string key with DI and can be scoped in child contexts as well.
- By default, the platform's default `IHistory` implementation is exposed with the name `"default"`. So `container.get(HistoryResource.keyFrom('default'))` will return the `IHistory` implemented by the browser's `History`
- Add a `history` field to `IRouteConfig`, like `{ name: string; scope: string }`. `scope` can be used to accommodate for retaining navigation state in potentially multiple wizards/modals that use the same `IHistory` implementation but have unrelated state.
    - If none is specified, `{ name: 'default', scope: 'global' }` is assumed. This is the standard browser implementation
    - If only the name is supplied and no scope, `'global'` scope is assumed. Can be useful for unit testing or having "normal" navigation capabilities in a non-browser environment
    - If only the scope is supplied and no name, `'scoped'` name is assumed. This would refer to a default implementation we can supply for people who want regular modals/wizards kind of stuff.

One such default implementation for scoped could be:

(it's practically identical to `BrowserHistory` impl but all entries and state sit in an object behind the corresponding scope property, and all methods have one additional argument `scope`)

```ts
export class ScopedHistory implements IHistory {
   public currentEntry: Record<string, IHistoryEntry>;
   public historyEntries: Record<string, IHistoryEntry[]>;
   public historyOffset: Record<string, number>;
   public replacedEntry: Record<string, IHistoryEntry>;

  public goto(path: string, scope: string, title?: string, data?: Object): void {
    // The scope is somehow supplied by the router which in turn gets it from the RouteConfig
    this.activeEntry[scope] = {...};
    this.setPath(path, scope);
  }
  public replace(path: string, scope: string, title?: string, data?: Object): void {}
  public redirect(path: string, scope: string, title?: string, data?: Object): void {}
  private setPath(path: string, scope: string, replace: boolean = false): void {
    if (this.currentEntry[scope] && this.currentEntry[scope].path === path) // etc
  }
}
```

And how the router might interact with that (of course grossly simplified):
```ts
export class Router {
    private historyLookup: Record<string, IHistory>;

    public forward(name?: string): void {
        this.getHistory(name).forward();
    }

    private getHistory(name?: string) {
        if (name === undefined) {
            name = 'default';
        }
        let history = this.historyLookup[name];
        if (history === undefined) {
            history = this.historyLookup[name] = this.container.get(HistoryResource.keyFrom(name));
        }
        return history;
    }
}
```

### Example:

```ts
@route({ path: 'one' })
export class PageOne { }

@route({ path: 'two' })
export class PageTwoFoo { }

@route({ path: 'two-bar' })
export class PageTwoBar { }

@route({ path: 'step-one', history: { scope: 'foo' })
export class FooWizardStepOne { }

@route({ path: 'step-two', history: { scope: 'foo' })
export class FooWizardStepTwo { }

@route({ path: 'step-one', history: { scope: 'bar' })
export class BarWizardStepOne { }

@route({ path: 'step-two', history: { scope: 'bar' })
export class BarWizardStepTwo { }
```
- Navigate to `one`
- Go forward to `one/two-foo`, viewport inside `PageTwoFoo` opens with `FooWizardStepOne`. url stays `one/two-foo`
- Click `next` in the wizard, viewport inside `PageTwoFoo` opens with `FooWizardStepTwo` (i believe this would be `replace`). url stays `one/two-foo`
- Hit the browser Back button, navigates back to `one` (with a regular history-tied wizard it would have gone back to `one/two-foo/step-one` from `one-two-foo/step-two`)
- Hit the browser Forward button, navigates to `one/two-foo` again and opens immediately at wizard step two, because that was the previous state of the wizard's history with scope `foo`
- Hit the browser Back button and go to to `one/two-bar`, viewport inside `PageTwoBar` opens with `BarWizardStepOne` (even though the path is `step-one`, the scope is different so it gets its own state)
- Click `next` in the wizard
- Click `finish` in the wizard which puts it back into `step-one` and navigates to some thank-you page.
- Hit the browser Back button, navigates back to `one/two-bar` and opens at `BarWizardStepOne`. Now technically the rest of the history for this wizard still exists, but there's no way for an end user to actually get access to those entries unless explicitly provided, because there is no Back button at step one.
- Go to `one/two-foo`, `FooWizardStepTwo` opens again

**Comment by davismj** [comment]
> Click `next` in the wizard, viewport inside `PageTwoFoo` opens with `FooWizardStepTwo` (i believe this would be `replace`). url stays `one/two-foo`

```
@route({ path: 'step-two', history: { scope: 'foo' })
export class FooWizardStepTwo { }
```

I think this is too verbose and has too much information. Also, less importantly the names are not straightforward. `@route({ name: 'foo-wizard-step-two' })` would tell the router to load `FooWizardStepTwo` into the default viewport. `@route({ name: 'foo-wizard-step-two', viewport: 'foo' })` would then tell the router to do this in the viewport named 'foo'.

`path` shouldn't be included, because `path` as a property should be used to match the url by definition. `history/scope` seems to be a less general way of scoping over `viewport`.

Contentions?

**Comment by bigopon** [comment]
I think our router API has gone far enough that we can start developing new ideas/proposals on top of it, instead of some hypothetical/v1 based APIs, let's close this and open a new one if we need to.
