### ISSUE TITLE
duplicate function deceleration in ITemplateFactory

### ISSUE THREAD

**Issue by avrahamcool** [aurelia/aurelia#349]
not sure if I missing something or if it's intentional.
I can see a lot of overloaded `createTemplate`, but it's seems that the line 29, and 30 are just duplicate.
Its not a bug, but it looks wrong.

https://github.com/aurelia/aurelia/blob/dbef7123ee2fd52b36a1d368e1386d0c85c59195/packages/jit/src/template-factory.ts#L29-L30

**Comment by fkleuver** [comment]
This happens to be intentional :)

The thing with overloading in TypeScript is that the last method signature is always hidden (and it should be compatible with all other overloads)

For example:

```ts
function doStuff(text: string): void;
function doStuff(digit: number): void;
function doStuff(textOrDigit: string | number): void {}
```

This only exposes the `text` and `digit` overloads: 
![image](https://user-images.githubusercontent.com/9655331/50427460-313bab00-08a9-11e9-8f4a-54777d14b9dd.png)
![image](https://user-images.githubusercontent.com/9655331/50427461-3a2c7c80-08a9-11e9-99db-b7e9c76f892c.png)

We want to give users the benefit of strong typing when they pass a precise argument type in (which is what the overloads are for), but we also want to give users the flexibility of passing in less precise types (which would be more consistent with vCurrent). So in this case we need to duplicate the last overload:
```ts
function doStuff(text: string): void;
function doStuff(digit: number): void;
function doStuff(textOrDigit: string | number): void;
function doStuff(textOrDigit: string | number): void {}
```

Only then it becomes publicly visible

![image](https://user-images.githubusercontent.com/9655331/50427468-647e3a00-08a9-11e9-8843-001ac24e2ca2.png)

**Comment by avrahamcool** [comment]
Thanks for the detailed explanation. :)
