### ISSUE TITLE
CSS module support

### ISSUE THREAD

**Issue by thomas-darling** [aurelia/aurelia#374]
# 💬 RFC

This is a proposal for how we could provide seamless support for [CSS modules](https://github.com/css-modules/css-modules) in Aurelia.
I'll leave studying the benefits of CSS modules as an exercise for the reader.

> There are of course alternatives that should be explored too:
>
> * Using native Shadow Dom - any plans for this in vNext?
>
> * Using generated attributes to scope the CSS, as in Angular - quite clever, actually!
>    https://angular.io/guide/component-styles#inspecting-generated-css

While this seem like something that might belong in a plugin, we'll need to make sure we have the right hooks and supporting features in Aurelia itself to make it work. And I really think this is a key feature - CSS is one of the great problems of frontend development, so if we can solve this nicely, that would be a huge win for Aurelia. Of course, we could probably do this at run time too, but for performance reasons, I think doing it at build time would be preferable.

I have no experience writing Webpack plugins, but I think this should be possible, and it would provide a _really_ awesome developer experience. With a Visual Studio Code plugin, it would even be possible to provide autocompletion for the class names - including the `.`-separated ones.

My goal here was to make [CSS modules](https://github.com/css-modules/css-modules) as natural to work with as normal CSS, and I think this achieves that. Feel free to comment and let me know what you think - it's just an idea so far :-)

## 🔦 Context

Let's assume the following:
* We have a component named `foo`, implemented by the files `foo.html` and `foo.css`.
* We use Webpack to build the project.
* We use the [css-loader](https://www.npmjs.com/package/css-loader) with the [modules](https://www.npmjs.com/package/css-loader#modules) option enabled.
* We use the [aurelia-binding-loader](https://www.npmjs.com/package/aurelia-binding-loader) to require CSS modules into the binding context of our views.
* We use a hypothetical new Webpack plugin to transform our view templates during build...

## 💻 Examples

The following examples illustrate how this would work, and the transformations that would be needed.

> Note that to get _exactly_ those nice class names shown here in the output, you'd need to customize the name generation a little bit. However, that is purely a CSS modules thing, and how you want your generated class names to look, isn't really relevant in the context of this proposal.

---

Classes are local by default, and the class names in the template are verified against the CSS file, to ensure no class names are misspelled or missing. If a class is found to be missing, the build fails.

**In the original template**
```html
<div class="header"></div>
```

**In the build output**
```html
<div class="header__a5f3"></div>
```

---

If we disable verification, any class name not found in the local stylesheet can be assumed to be global and left unchanged. This makes it easy to mix local and global classes, but also makes it impossible to detect misspelled or missing classes. 

**In the original template**
```html
<div class="header text-headings-large"></div>
```

**In the build output**
```html
<div class="header__a5f3 text-headings-large"></div>
```

An alternative option would be to introduce a customizable whitelist of class name prefixes, such as `ux-`, so that any class name starting with one of those prefixes is assumed to be global, and left unchanged and unverified.

---

Classes from other stylesheets can be imported by prefixing the class name with the `.`-separated path to the stylesheet. Note that this path should be relative to one of the base paths specified in the config for our hypothetical plugin. If the path resolves to multiple stylesheets, and a matching class is found in more than one, the build fails.

**In the original template**
```html
<div class="header text.headings.large"></div>
```

> This imports the class `large` from `./${basePath}/text/headings.css`.<br>

**In the build output**
```html
<div class="header__a5f3 text_headings_large__6ef4"></div>
```

---

Binding expressions can be used too, but only in the class name itself, not in the path.
This constraint is just to keep things simple, although we could probably make it work in the path too. That would just mean the `<require>` statements cannot be added at build time, as the file path then depends on the binding - so we must import the CSS files at run time.

**In the original template**
```html
<div class="header state-${state} text.headings.${size}"></div>
```

**In the build output**
```html
<div class="header__a5f3 ${$styles_1['state-' + state]} ${$styles_2[size]}"></div>
```

---

Same goes for conditional classes - that can work too.

**In the original template**
```html
<div class="header ${expanded ? 'expanded' : ''}"></div>
```

**In the build output**
```html
<div class="header__a5f3 ${expanded ? $styles_1.expanded : ''}"></div>
```

On a side note, I think we should allow the _else_ part, i.e. the `: ''`, to be omitted in binding expressions. I know that's not in line with JavaScript, but this pattern of _only if true_ is so common here, that it feels a little bit pointless that we are forced to always write that _else_ part.

---

And finally, to make the above work, the `<require>` statements for the stylesheets will be added automatically, with the path for the stylesheet for the current component determined by convention, just like the view and view model - i.e. same file name, in same folder, but with a different extension. 

Note that we rely on the [aurelia-binding-loader](https://www.npmjs.com/package/aurelia-binding-loader) plugin to require the CSS module into the binding context of the view. The property names to which those are assigned are not really important, as they can be considered an implementation detail.

**In the build output**
```html
<require from="./foo.css!bind" as="$styles_1"></require>
<require from="resources/styles/text/headings.css!bind" as="$styles_2"></require>
```

This assumes a build plugin configuration that looks something like this:

**The configuration for our hypothetical plugin**
```js
{
    // The base paths to try when resolving a dot-separated class name to a file path.
    basePaths:
    [
        "resources/styles",
        "resources/theme"
    ],

    // True to disallow global styles and verify that classes specified in templates actually
    // exists in the stylesheets, false to allow global styles and disable verification.
    verify: true | false
}
```

---

Of course, any `<require>` statements explicitly specified in the template should take precedence. This allows you to override the convention and explicitly specify the file containing the local styles for the component, or to explicitly specify the property name on the binding context, to which the CSS module should be assigned - just in case you need to do something really creative with it. 

Note that we automatically rewrite the require statements to include the plugin needed to require the CSS module into the binding context of the view. I think Aurelia should maybe just support this out of the box though, so we won't need the [aurelia-binding-loader](https://www.npmjs.com/package/aurelia-binding-loader) plugin.

**In the original template**
```html
<require from="./styles.css"></require>
<require from="resources/styles/framework/base/text.css" as="typography"></require>

<div class="header typography.title"></div>
```

> This imports the class `header` from `./styles.css` and the class `title` from `resources/styles/long/path/to/stylesheet.css`, exposed as a `typography` property on the binding context. This also saves you from typing `framework.base.text.title` as the class name.

**In the build output**
```html
<require from="./styles.css!bind" as="$styles_1"></require>
<require from="resources/styles/framework/base/text.css!bind" as="typography"></require>

<div class="header__e3zw framework_base_text_title__i4w8"></div>
```

---

And if you need the class names in JavaScript, you can of course just `import` the CSS file there, exactly as you'd normally do with CSS modules.

**Comment by fkleuver** [comment]
Apologies for the silence - there is a lot to think about here!
Really appreciate you taking the times to write up such a thorough RFC however :)

I'll try to address the main points one by one. Feel free to point it out if I missed any, misunderstood any, or in some way did injustice to any.

---
* Using native Shadow Dom - any plans for this in vNext?

Yes, as a matter of fact we are doubling down on native in vNext by dropping slot emulation. This is to make the framework smaller, more performance and give us less maintenance overhead. There are some excellent polyfills out there and we might add some plugins as convenience wrappers though. We will see based on what works and what doesn't.

So to get scoped CSS, all you need to do is put `@useShadowDOM` on top of your custom element and done.

---
* Using generated attributes to scope the CSS, as in Angular

It is my understanding that Angular is using their own CSS parser (just like they use their own HTML parser), including an AST. I am playing with the thought of putting a CSS parser in the JIT (and AST in the runtime) as well. This would allow us to make CSS a first-class citizen in the framework, make binding to it much easier, and provide a lot of other benefits as well (such as re-generating scoped names, etc).
However there would be a significant amount of work involved so we will have to see how things play out and what needs priority. Definitely on the TODO list for at some point, though.

---
* If a class is found to be missing, the build fails.

* If we disable verification, any class name not found in the local stylesheet can be assumed to be global and left unchanged. 

* An alternative option would be to introduce a customizable whitelist of class name prefixes

I can see legitimate uses cases for all of these scenarios, and ultimately I don't think the complexity lies in making any of these configurable. So, I think (if we went down the path of a CSS parser + AST) we could fairly easily have all these options and make them configurable. I think that would be best.

All in all you raise a few excellent points here about edge cases, some of which we already discussed internally a while ago. It is incredibly helpful to have them properly listed and addressed in an RFC, so that we can work off that and have a proper place to continue discussing them.

---
* Binding expressions can be used too, but only in the class name itself, not in the path. This constraint is just to keep things simple, although we could probably make it work in the path too. That would just mean the <require> statements cannot be added at build time, as the file path then depends on the binding - so we must import the CSS files at run time.

I think if we're talking about AOT the same principles would be applied as when statically analyzing and replacing decorators: simply resolve everything that can be analyzed statically, leave the rest for run time. Principle of "best effort".

The JIT should be able to handle all of this. AOT simply resolves as much as possible at build time.

Although I'm not sure how bound paths would work out in practice. That means we would need a loader at runtime, something we decided to stop doing in vNext. This could work via requirejs plugin though. Need to think about this a bit more, try things out, etc. It's definitely an interesting idea to bind to paths as it would add a lot of power.

* Same goes for conditional classes - that can work too.

Those are really just binding expressions, so I suppose the same ideas apply as above.

---
* On a side note, I think we should allow the else part, i.e. the : '', to be omitted in binding expressions

This is another thing we've discussed at some lengths internally. We never quite finished that discussion as we weren't able to settle on any particular syntax. For one, we're trying to keep our JIT JavaScript parser as ES spec compliant (for the subset that it implements) as possible.

A similar thing can be accomplish with logical AND: `condition && 'some-class'`. However that would leave `'false'` in the class list if the condition was not met. Perhaps some CSS specific rule could be applied to transform it.

Are there any other frameworks providing such a shorthand?

---
* And finally, to make the above work, the <require> statements for the stylesheets will be added automatically, with the path for the stylesheet for the current component determined by convention, just like the view and view model - i.e. same file name, in same folder, but with a different extension.

Yep, this makes good sense.

---
* Of course, any <require> statements explicitly specified in the template should take precedence.

Why precedence instead of both? You can also `<require>` multiple stylesheets. It would make sense to me to *always* look for a convention based match *on top of* any manually `<required>` stylesheets. Or does that sound silly?

* Note that we automatically rewrite the require statements to include the plugin needed to require the CSS module into the binding context of the view. I think Aurelia should maybe just support this out of the box though, so we won't need the aurelia-binding-loader plugin.

@EisenbergEffect has been working on some "interpreter" in DI that, if I'm not mistaken, would enable this sort of thing (if the appropriate plugins were included) out of the box via DI. I would need some more use cases / examples though to be able to efficiently do any concrete work on this, in particular with respect to what needs to happen at build time / by a bundler plugin, vs what needs to (or can) happen at runtime / jit by a loader plugin.

---
* And if you need the class names in JavaScript, you can of course just import the CSS file there, exactly as you'd normally do with CSS modules.

Yup, also makes good sense.

**Comment by EisenbergEffect** [comment]
@thomas-darling Please have a read through of this RFC: https://github.com/aurelia/aurelia/issues/524 I propose a general mechanism for integrating CSS solutions. I cover CSS Modules there.

**Comment by EisenbergEffect** [comment]
Closing as support for CSS Modules Processor is now merged to master.
