### ISSUE TITLE
[RFC] Application Startup

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/aurelia#397]
# 💬 RFC

Provide a simple and terse way to startup Aurelia, but without sacrificing power and flexibility.

## 🔦 Context

In Aurelia vCurrent, I've always felt that the startup model was clunky and verbose. We'd like to have something a bit cleaner for vNext. It should be very easy for a beginning to write a few lines of code but also for an advanced user or someone writing a large/complex application to be able to get things setup precisely as needed.

## 💻 Examples

Below is a basic example of creating an Aurelia instance, specifying the HTML element to initialize the app with, the root component to use and the list of plugins for the framework.

#### Minimal Configuration

```TypeScript
import { BasicConfiguration } from '@aurelia/jit-html-browser';
import { Aurelia } from '@aurelia/runtime';

new Aurelia({
  host: 'my-host-element',
  component: MyRootComponent,
  plugins: [BasicConfiguration]
}).start();
```

**Open Question**: Should we export an alternate version of `Aurelia` from `@aurelia/jit-html-browser` with the `BasicConfiguration` already specified or would that option create confusion?

```TypeScript
import { Aurelia } from '@aurelia/jit-html-browser';

new Aurelia({
  host: 'my-host-element',
  component: MyRootComponent
}).start();
```

#### Advanced Configuration

```TypeScript
import { BasicConfiguration } from '@aurelia/jit-html-browser';
import { DebugConfiguration } from '@aurelia/debug';
import { Aurelia } from '@aurelia/runtime';
import { AnotherPluginConfiguration } from 'another-plugin';
import { someFancyPlugin } from 'some-fancy-plugin';

new Aurelia({
  host: document.getElementById('my-host-element'),
  component: MyRootComponent,
  plugins: [
    BasicConfiguration,
    DebugConfiguration,
    AnotherPluginConfiguration,
    someFancyPlugin(config => {
      config.doSomething();
    })
  ]
}).start();
```

**Open Question**: In addition to this object-literal-based configuration, should we also provide a fluent api?

```TypeScript
import { BasicConfiguration } from '@aurelia/jit-html-browser';
import { Aurelia } from '@aurelia/runtime';

Aurelia
  .at('my-host-element')
  .using(MyRootComponent)
  .plugin(BasicConfiguration)
  .start();
```

**Open Question**: Should we also have the html-jit version of this or is that confusing?

```TypeScript
import { Aurelia } from '@aurelia/jit-html-browser';

Aurelia
  .at('my-host-element')
  .using(MyRootComponent)
  .start();
```

## Related

* What should the `enhance` API look like?
* What about switching application roots?
* What about temporarily or permanently shutting down a running application?

**Comment by fkleuver** [comment]
I'll PR something and link to it in this RFC so we can see how it plays out in practice. There are a few caveats here and there which are best illustrated with actual code.

### The fluent API
I do like the `.at` and `.using` but it also feels like it adds learning curve for not matching up to the object literal's arguments.
My initial idea would have been `Aurelia.host('my-host-element').component(MyRootComponent).start()`
Perhaps we should rename the literal properties instead? `.app({ at: 'my-host-element', using: MyRootComponent })`
One could argue endlessly over which specific names to pick, but for me the bottom line is imo the fluent API should match the object literal properties.

### The enhance API
My initial thought is simply add an `enhance: true` to the object literal API and an `.enhance()` to the fluent one. But in keeping consistency that would result in `.enhance().start()` whereas in vCurrent `.enhance()` is an *alternative* to `.start()`. And then you get no difference in `.stop()`ing an enhanced or a regular version.

I think for this reason it can be worth deviating from vCurrent. `.enhance()` does *not* start the application, `.start()` is the only way to start an application. Everything else just adds configuration. That feels like a more robust API to me.

### Switching application roots
In vNext, the root is in fact nothing special. It is just a "containerless" custom element whose container is supplied via the Aurelia API.

By that logic, I think "switching root" in itself doesn't have to stand out so much as a special operation. It would simply be a matter of stopping, re-configuring, and starting again. You could set a different root component, or a different host, or re-configure something else, or do all of it at the same time.

But switching root is usually related to having a public vs. an authenticated section. In vCurrent there's a fair amount of difficulty getting rid of state. The only reason you don't just start/stop between two different Aurelia instances is because there's no first-class support for that concept in vCurrent.

In vNext there is no `configure` that's "magically" called by some external loader in a non-transparent manner. No, *you* are in control, *you* create and start Aurelia. It's easy to configure multiple standalone Aurelia's and start/stop them at will.
With that in place, I doubt anyone really needs a "setRoot" operation by vCurrent's definition.

If you need something more sophisticated with *some* shared state but not everything (e.g. a single store but two different routers) you can have one root Aurelia encapsulating that, and dynamically start/stop different Aurelia's *inside* the top-level Aurelia (yes, that's aurelia-ception). You can even define a custom element that starts/stops a nested aurelia, or dynamically do this via compose.

### Temporarily/permanently stopping an instance
We already have the temporary variant. It retains some state, such as DI registrations and certain caches. I'd definitely say we also need a permanent variant with a `$dehydrate` to do the opposite of `$hydrate`.
Every other framework has ways to really *destroy* components, we need it too.

**Comment by bigopon** [comment]
We need the equivalent of `plugins` in terms of DI, so I would suggest using `dependencies` or `globalDependencies` instead, and we kind of need it. Agree about permanently stopping an Aurelia instance.

**Comment by EisenbergEffect** [comment]
@fkleuver Definitely agree on keeping the naming the same between the two APIs. Also, I like the idea for how to handle `enhance`. Good points about switching roots too. That's the way I would tend to handle it. I was thinking that we might want to make `Aurelia` implement `IDisposable` and then maybe internally that calls through to the `$dehydrate` among other things.

@bigopon The `plugin` API just passes through to DI as an `IRegistry`, so I'm not sure that we need anything else there. Is there something I'm missing?

**Comment by bigopon** [comment]
@EisenbergEffect I meant the wording of it, but on a second thought, `dependencies` doesn't capture the whole meaning. So probably `plugins` is better.

**Comment by akircher** [comment]
I don't have strong feelings here but these are some thoughts:

- Do we really need a matching config and fluent api off the bat? It seems like having both is just more documentation headache and cause confusion?  I would just pick one and add one later if anyone asks for it.

- Could we have sensible defaults? In v1 my root components is `index.js` and `index.html`, my `host` is `<body>`.  It seems like if `host` and `component` are not we could come up with a good default convention.  This means our getting started documentation could just be:

```
<script src="aurelia2cdnurl.com">
<script>
import { Aurelia } from '@aurelia/jit-html-browser';
Aurelia.start();
</script>
```

- I like the idea of having Aurelia exported from both `jit` and `aot` but think it gets confusing if there is also one exported from runtime.  Can we just have the above two options since you do have to pick/use one of those two options right?  

- I don't really like `at` or `host`.  Can we use the same naming as the new router -  everything is a `component` and a `view-slot` (even the app itself)?  I don't care what the names are, I just think there is a chance for elegance here if we can use the same mental model as the router.

**Comment by HamedFathi** [comment]
@EisenbergEffect 

Please consider [this conversation](https://discourse.aurelia.io/t/aurelia-2018-q2-update-and-vnext-progress/1501/7) about ExcludePlugin.

However, you answered it:

> For plugins, we’ve opted to enhance the dependency injection container to handle this scenario. As pictured in the code sample above BasicConfiguration is a plugin that adds all the basic capabilities of the framework. However, the new mechanism and framework design allows you to add each piece individually, so you can add only what you want/need. When we enable AOT, we’re hopeful that we’ll be able to code-generate a plugin, specific for your app, that installs only the things you actually use, so you don’t have to do that by hand.

**Comment by fkleuver** [comment]
@akircher 

- Do we really need a matching config and fluent api off the bat?

The fluent API is more elegant I'd say for manual bootstrapping but the object API lends itself more for programmatically building a config (and would be familiar to users of other frameworks doing it like this). I feel the fluent one is more aurelia-esque though.

What would you say if we dropped the object api for now and went with fluent only instead? Or would you rather see it the other way around?

- Could we have sensible defaults?

Our plan was to let `aot` take care of these things, potentially supplemented by some lightweight require/webpack plugins that also know about these conventions and make the appropriate transformations at build time. So what you're seeing here now is in fact the verbose, convention-less API. When the other pieces are in place, there will be even less to configure.

- I like the idea of having Aurelia exported from both jit and aot but think it gets confusing if there is also one exported from runtime

Not jit and aot, but runtime and jit. The runtime is what you take if you'd use AOT and do not need the JIT (aot calls JIT at build time to pre-compile everything). It results in a very fast, lightweight app.

If you don't want to use AOT or you simply want to be able to parse/compile templates at runtime, you'll need the JIT. But only exporting `Aurelia` from the JIT means you always need to depend on the JIT, which is what we'd like to avoid. Does that make sense?

- I just think there is a chance for elegance here if we can use the same mental model as the router.

Definitely agree we should keep everything as consistent as possible. Either the router needs to be more like runtime in terms of API or vice versa. That's not set in stone yet. I am soon going to work on a proper activation mechanism that both `Aurelia` and the router can tap into, and that's when we'll also be looking into making everything more consistent.

**Comment by brandonseydel** [comment]
Aurelia.attach(MyApp).to(document.getElementById('app')).using(...plugins);

**Comment by brandonseydel** [comment]
Aurelia.enhance(document.getelementById('app').with(component).using(...plugins)

**Comment by brandonseydel** [comment]
all options have a configure api to pass in overrides also or just everything
Aurelia.configure( {app: blah, plugins: []}  );
Aurelia.configure(y=> y.app = blah; y.plugins = []; yadayda)

**Comment by ghiscoding** [comment]
> davismj added this to Discussion in Prospoals 22 hours ago
@davismj Totally out of subject, but I think it should be **Proposals**... 🤣

**Comment by davismj** [comment]
**Fluent API**

I agree with Fred, names should match. Less to doc, less confusion. I don't like opting in and out of new. It should be new in both or neither. I vote both.

```ts
import { Aurelia } from '@aurelia/jit-html-browser';

const app = new Aurelia({
  host: 'my-host-element',
  component: MyRootComponent
}).start();

new Aurelia()
  .host('my-host-element')
  .component(MyRootComponent)
  .start();
```

**Basic Config**

> the `BasicConfiguration` already specified or would that option create confusion?

The tricky thing with this is that it would be difficult to remove.

```ts
new Aurelia().start(); // want basic config
new Aurelia().plugins('au-tables').start(); // still want basic config
new Aurelia().plugins(CustomConfig, 'au-tables').start(); // dont want basic config
```

That said, I think BasicConfiguration options should be used as the default when not manually overridden.

**Enhance**

I'm not sure what the difference would be for enhance, in this case. It seems that the vNext app startup is more enhance-like already.

**Switching Root**

To add to @fkleuver's assessment, I think the key issue in vCurrent root switching is based around the router. I'm thinking the idea of switching roots will be less useful with a singleton router.

As Fred said, the key use case is a login wall. I think it needs its own small spec.

**Sensible Defaults**

@akircher is right, we need sensible defaults. Against @fkleuver's assessment, I believe that *both* the verbose and terse versions ought to be specced side-by-side. There's no rule that says you can't add later, but I think it's a good practice to have them up front, as soon as possible.

**App Roots**

**Comment by brandonseydel** [comment]
To the opting in and out I would suggest not reading to much into it with typescript.  The intellisense will be the shepherd that guides people to these before unfounded niceties (even though we should document).  Just image in the .NET realm all of the fluent and non fluent versions of apis.  Everything has a fluent option anymore.  Removing the option to type less for what little it is to code into the framework doesn't seem necessary.

I know commonality is what your after, but I also think that providing this as a direct access to root node would also be very nice. 

 **(No configuration method involved in these - Straight to the view model)**

**AU-APP** - REPLACE CONTENT INSIDE AFTER MOUNT
- Basic configuration examples

Convention
``` html
<div au-app /></div> 
``` 
Configuration
``` html
 <div au-app='./module' />
```  

- More advanced configurations
```html 
<di au-app-'./module' au-options='{}' />
```

- Extreme fall back to script attaching.



**AU-ENHANCE** - USE CONTENT INSIDE AS VIEW

- Convention
``` html
<div au-enhance>
<button click.delegate='asdfasfd' />
</div> 
```

- Configuration

``` html
<div au-enhance='component'>
<button click.delegate='asdfasfd' />
</div> 
```


Full aurelia app would boot with no effort

``` html
<html>
<head>
</head>
<body>
<div au-app='TestComponent' />

<-- aurelia -script tag-->
<-- your app tag -->
</body>
</html>
```

**Comment by fkleuver** [comment]
Not directly related to anything in particular, but I should point out that with recent lifecycle work, `.start()` and `.stop()` return `ILifecycleTask` instead of `Aurelia`.

In effect:

```ts
// Completely fine
new Aurelia().register(BasicConfiguration).app({ host, component }).start();

// whoops! au is a task.. not what you might expect
const au = new Aurelia().register(BasicConfiguration).app({ host, component }).start();

// Do this instead, if you need au
const au = new Aurelia().register(BasicConfiguration).app({ host, component });
au.start();
```

However, I like to actually await that task. I suppose this is a bit of a habit from all those unit tests where i start/stop Aurelia sometimes multiple times in a row. And because it overall seems like a more sound approach.

```ts
// Here is how I start up my vNext app at work
(async function () {
  const au = new Aurelia()
    .register(
      BasicConfiguration,
      OtherConfiguration,
      EvenMoreConfiguration
    )
    .app({ host, component });

  await au.start().wait();
}().catch(console.error);
```

Okay, so we've got some IIFE going on that may look intimidating to some? I'm not sure.
I personally love this particular way of starting up the app because it makes it easy to opt in to storing `Aurelia` in some global variable as well as inspect the end state while debugging, because the start task is awaited in-inline.

What do others think about the above snippet for bootstrapping code?

**Comment by 3cp** [comment]
@fkleuver I guess I need to update our skeleton to?

```js
const au = new Aurelia()
  .register(BasicConfiguration, DebugConfiguration)
  .app({
    host: document.querySelector('app'),
    component: new App()
  });

// for debug
global['au'] = au;

au.start().wait().catch(console.error);
```

**Comment by EisenbergEffect** [comment]
Probably just remove the global `au`.

**Comment by 3cp** [comment]
@EisenbergEffect do we need that error catch?

```js
new Aurelia()
  .register(BasicConfiguration, DebugConfiguration)
  .app({
    host: document.querySelector('app'),
    component: new App()
  })
  .start()
  .wait()
  .catch(console.error);
```

**Comment by EisenbergEffect** [comment]
I’ve just been doing `new Aurelia({ … }).start()`. Not sure that we need that catch in app code.

**Comment by EisenbergEffect** [comment]
@fkleuver probably knows better on that though.

**Comment by 3cp** [comment]
I see, the error (at least for exception in my View Model code and html template) is still logged in browser console without that explicit catch line.

`.wait().catch(err => console.error('got error: ' + err.message));` didn't print anything new.

@fkleuver is that `wait()` only capture nasty Aurelia internal error?

**Comment by fkleuver** [comment]
It doesn't log anything that the browser wouldn't, but it does prevent the error from crashing the page and it also satisfies some linter settings that disallow floating promises

**Comment by 3cp** [comment]
> satisfies some linter settings that disallow floating promises

That would not an issue if `.wait()` is not present in code.

@fkleuver do you recommend to add the extra two lines to end users' apps?

**Comment by fkleuver** [comment]
I guess not

**Comment by Sayan751** [comment]
@bigopon I am closing this issue, as the current app start API is straightforward. Irrespective whether a resource, service or plugin is registered, there is a uniform API for all for registration.

**Comment by bigopon** [comment]
Yup we solved this with our current startup apis.
