### ISSUE TITLE
[Bug] Compose Should Transfer Attributes to Composed Elements

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/aurelia#422]
# 🐛 Bug Report

Any non-white-listed attribute that's placed on the `au-compose` element itself should be transplanted onto the actual composed element.

## 🤔 Expected Behavior

Given the following HTML:

```XML
<template repeat.for="space of spaces">
  <au-compose :subject="space" class="space-container ${space.isActive ? 'active' : ''}"></au-compose>
</template>
```

Assuming that the subject produces a `my-space` custom element and that `space.isActive === true`, at runtime we should see the following composed in the DOM:

```xml
<my-space class="space-container active"></my-space>
```

## 😯 Current Behavior

Currently, no attributes are transplanted onto the composed element. We would see the following in the DOM:

```xml
<my-space></my-space>
```

## 💁 Possible Solution

I haven't dug into the code to see what exactly is going on yet. It's either in the `au-compose` element code or in the `createElement` code. The `createElement` function should have the core capability of doing this so there's probably either a bug there or in how the `au-compose` element is collecting the initial bindings or passing them along.

## 🔦 Context

Due to the current issue, additional HTML elements have to be constructed around composed elements to handle the `class` scenario. This is workable but can create some issues with layout. However, beyond `class`, any attribute should work and if the custom element needs custom attribute bindings, this bug creates a block for the developer.

**Comment by fkleuver** [comment]
@EisenbergEffect The problem here is that the template compiler will try to compile whatever is on `au-compose` before it is even instantiated, so what `au-compose` deals with at that point is already compiled instructions which are compiled against the context of compose.
Meaning, every binding command is seen as a native html attribute even if they may in fact be bindable properties on the subject.

So, compilation needs to be avoided for unknown attributes on au-compose. That means the compiler needs to be specifically aware of `au-compose`. To be honest though, I am not necessarily against that. The template binder sits in `jit-html`, `au-compose` in `runtime-html`, so they're already coupled to the same runtime type and the compiler can import compose just fine.

Doing that, however, creates a hard dependency from the compiler to au-compose. In order to avoid that there either needs to be some extension point in the compiler where behaviors can dynamically be registered (thereby retaining tree shaking capabilities and such) and/or custom elements simply need a static hook like `compiling()` and perhaps even `compiled()` where they can build their own symbol in a custom way.

That in turn creates a dependency from runtime to jit specific classes (obvious no-no there), so I'm thinking as an addition to `@attributePattern` and `@bindingCommand` to also have a `@resourceCompiler` or some such.

Thoughts?

**Comment by EisenbergEffect** [comment]
So, `@resourceCompiler` would allow an element to plug into the compilation process, which in this specific case, instances of `au-compose` would use to siphon off non-compose attributes, so that it could pass those along to whatever is being composed. Is that the idea?

**Comment by fkleuver** [comment]
Broadly speaking, yeah. But it probably should be a separate class and not the actual custom element as I think instantiating a custom element for the purpose of having it compile itself is a bit weird to say the least :)

**Comment by EisenbergEffect** [comment]
Right, maybe the decorators associated the resource compiler.

**Comment by fkleuver** [comment]
Does this work in vCurrent by the way? How is it handled there?

**Comment by EisenbergEffect** [comment]
Nope, it doesn't work in vCurrent. vCurrent works very different in general. This is attempting to correct a number of mistakes in the way vCurrent's compose work. For example, vCurrent doesn't compose an element it just shoves the view into the compose element, so there's inconsistency when composing an element vs. using it directly. I'd like it to work the same. Enabling pass through bindings is the next step with that.

**Comment by fkleuver** [comment]
>Enabling pass through bindings is the next step with that.

That's what I was thinking about as well, this sounds more like pass through bindings, which is kind of a standalone thing.

I think what might be a better approach is to implement pass through bindings first, and from there on let `au-compose` utilize the functionality (perhaps with a few tweaks) to enable this particular scenario.

Does that sound sensible?

**Comment by EisenbergEffect** [comment]
That sounds like a good idea to me :) I believe there was another request for pass-through bindings independent of this.
