### ISSUE TITLE
Dynamic routing: parameter syntax [RFC]

### ISSUE THREAD

**Issue by jwx** [aurelia/aurelia#459]
# 💬 RFC

I'm revising the "url syntax" for dynamic routing and would like to ask for your opinion regarding the syntax for parameters. The principle is that it's possible to pass parameters to a component in a href/url by putting them in parantheses:
```html
<a href="book(123)">Show book component and pass parameter '123'</a>
```
In addition it's possible to pass more than one (ordered) parameter or to pass named parameters.
```html
<a href="book(123,sv)">Show book component and pass parameter list ['123', 'sv']</a>
<a href="book(id=123,lang=sv)">Show book component and pass parameter object { id: '123', lang: 'sv' }</a>
```

I've currently got three alternatives:

1) "Function syntax"
```html
<a href="book(123)">Show book component and pass parameter '123'</a>
<a href="book(123,sv)">Show book component and pass parameter list ['123', 'sv']</a>
<a href="book(id=123,lang=sv)">Show book component and pass parameter object { id: '123', lang: 'sv' }</a>
```

2) "Query syntax"
```html
<a href="book(123)">Show book component and pass parameter '123'</a>
<a href="book(123&sv)">Show book component and pass parameter list ['123', 'sv']</a>
<a href="book(id=123&lang=sv)">Show book component and pass parameter object { id: '123', lang: 'sv' }</a>
```

3) "Object syntax"
```html
<a href="book(123)">Show book component and pass parameter '123'</a>
<a href="book(123,sv)">Show book component and pass parameter list ['123', 'sv']</a>
<a href="book(id:123,lang:sv)">Show book component and pass parameter object { id: '123', lang: 'sv' }</a>
```

I'd _really_ appreciate it if you could let me know which one of the above, or any other suggestion, you prefer. Just post a quick reply here with your opinion as soon as possible. Thank you!

**Comment by bigopon** [comment]
I think both function and query syntax look nice, as `=` captures the meaning of value better than `:` in JS/TS. Query syntax with `&` is not as read friendly as `,` in function syntax, so if there is no issue with `,`, I would say we should go for function syntax.

**Comment by brandonseydel** [comment]
+1 for #2

**Comment by jwx** [comment]
> comma delimited for implied parameters and & for named

Damn you, @brandonseydel! ;)

**Comment by Vheissu** [comment]
My vote is for option 2 and option 3. If I had to choose between the two, I would lean for option two purely based on the fact that it nicely resembles how you would work with URL's outside of the context of a router.

**Comment by bigopon** [comment]
having query syntax could affect interoperability of url as well, I think we should avoid it, if it's not used in "standard" way

**Comment by davismj** [comment]
(a) I don't think we should support the array syntax at all

```html
<a href="book(123,sv)">Show book component and pass parameter list ['123', 'sv']</a>
```

It doesn't bring anything to the table except having to go check what order your arguments are. It's just one more thing that could break.

(b) Dwayne has it right that 2 and 3 are both fine, but my vote is actually for object syntax. I think the query syntax would introduce confusion about what is actually happening. Someone would see it and think "oh this is some kind of query string something or other." With the object syntax, everyone would see it and say "oh that's something new, but familiar."

**Comment by Alexander-Taran** [comment]
I still think that URL structure should convey the meaning of it.
As in "/" means nesting. It is universal directory drill-down. 
```parent-view-port/child-view-port```
`+` is unusable in URLs for proper SEO
I don't recall what I came up with in talks with @jwx .
but maybe a comma would do.
brother-view-port,sister-view-port
() is a good usage for parameters it does convey function with parameters

**Comment by ErikSchierboom** [comment]
My preference is to use the function syntax, as to me the comma makes it easier to discern between the different parts; the & version is much harder to read IMHO.

**Comment by CuddleBunny** [comment]
I prefer function syntax myself, since if I want to write query syntax I would just use traditional routing instead. Having the function alternative to use where appropriate would be nice. I don't mind the object syntax, but I think the function version feels more like a URL while providing some distinction from a regular query URL.

**Comment by avrahamcool** [comment]
[not directly related to these RFC - but this is the best place I found to add my request]

based on a [recent question](https://discourse.aurelia.io/t/get-query-parameters-in-app-module/2780) I asked in the discourse channel.

would it be possible for aurelia vNext to parse the query parameter as early as possible?

it's a legit use case to access query parameters in the `App` module.

taking it even one step further, thew query parameters should be available even in the `Main` module.
to allow different settings of the `aurelia` object based on different query parameters.

CLARIFICATION;
when I use the term query parameters, I'm not referring to client side routing parameters (because those parameters can be parsed only after the route table is configured).
I'm talking about "regular" URL parameters.

**Comment by m-gallesio** [comment]
This would be equivalent to `route-href="route:book;params.bind:{id:123,lang:'sv'}"`, right?
Personally both Function and Object syntax seems fine as they more closely resemble how a JS function is called.
Of the two I slightly prefer Object since it is closer to the JS object syntax which will be used in the lifecycle hooks to access route parameters (at least in V1, I have not been following recent developments of V2).
(As an aside, C# can use this exact Object syntax for named parameters so it does have a precedent in some languages.)

**Comment by 3cp** [comment]
Suggest the object form `book(id:123,lang:sv)` should also tolerate optional extra curly braces `book({id:123,lang:sv})`.

**Comment by shahabganji** [comment]
I think for the users, Object syntax looks more familiar, not only they used to such syntax from other programming languages, but it also resembles the kind of syntax we have in aurelia current for params.bind. however, I'd rather it has the curly braces for less confusion with function calls.

**Comment by Sayan751** [comment]
@jwx Can this be closed?

**Comment by jwx** [comment]
Implemented.
