### ISSUE TITLE
[Feature] Support defining replaceable templates in nested elements

### ISSUE THREAD

**Issue by michaelw85** [aurelia/aurelia#479]
# 🙋 Feature Request

Add support to be able to manipulate inner slots/replaceable template(s) for nested custom elements.

(If you think it's stupid or an edge case please dismiss/close this feature request)

## 🤔 Expected Behavior

It should be possible to define a replaceable template or slot and pass it to nested components. 

## 😯 Current Behavior

Not supported

## 💁 Possible Solution

- Be able to take a slot and place it inside a replaceable template
```html
// Use component
<my-component>slot content</my-component>

// Component:
<template>
  <nested-comp>
    <template replace-part="xyz"><slot></slot></template>
  </nested-comp>
</template>
```

- Possibility to nest replaceable templates
```html
// Use component
<my-component><template replace-part="abc">defines xyz</template></my-component>

// Component:
<template>
  <nested-comp>
    <template replace-part="xyz">
      <template replaceable part="abc"></template>
    </template>
  </nested-comp>
</template>
```

## 🔦 Context

How I came up with this idea.

I am working on a component library. While working on a menu I thought it would be very flexible to be able to define the markup of the menu item. The menu is build up of a ul>li>a structure by default.

So I have a nested custom list component which has a replaceable template. This replaceable template defines the content of the list item. I attempted to manipulate this content by defining the replace template using the menu component and tried using a slot and both are not supported in the current Aurelia version.

## 💻 Examples

Top level fictive custom element (`my-component`)
```html
<template>
  <my-nested-component>
    <template replace-part="define-me">
      // define the default content
    </template>
  </my-nested-component>
</template>
```

Consuming my-component
```html
<my-component>
  <template replace-part="define-me">
    // Define tpl for nested component
  </template>
</my-component>
```

**Comment by bigopon** [comment]
@fkleuver for your awareness since you are touching the tests related to this as well

**Comment by artmasa** [comment]
@michaelw85 what about this approach when you just want to inherit the template?
```
<template>
  <nested-comp>
    <template replace-part="xyz" replaceable part="xyz">
    </template>
  </nested-comp>
</template>
```
In this case when no other template is defined or necesary to replace the base template.

**Comment by JontyMC** [comment]
@michaelw85 I think this is the same use case I was asking about in this post https://discourse.aurelia.io/t/replace-template-in-child-component/745

I have a gist to show the issue https://gist.run/?id=cbe9c187550bbceb8a8b3353f0e943c8

**Comment by michaelw85** [comment]
@JontyMC Yes exactly the same request

**Comment by fkleuver** [comment]
@artmasa Wouldn't it be more intuitive to have that as the default behavior, without having to explicitly declare the `replaceable` as a `replace-part`?

e.g.

```html
<template>
  <nested-comp>
    <template replaceable part="xyz">
    </template>
  </nested-comp>
</template>
```

If no `replace-part="xyz"` exists, then the `replaceable` is simply not replaced. Does that make sense?

**Comment by fkleuver** [comment]
@michaelw85 

**slot inside replaceable template**
```html
// Use component
<my-component>slot content</my-component>

// Component:
<template>
  <nested-comp>
    <template replace-part="xyz"><slot></slot></template>
  </nested-comp>
</template>
```

Woah. People never cease to amaze me with exotic slot/replaceable use cases. 

I'm not sure if that is possible though. The usage of `my-component` would need to be attached to the DOM for the slot content to be projected into the `replace-part`, but at that point the `replace-part` would already have been extracted from that template so the slot wouldn't exist there anymore.

I'll try it nonetheless because it's a very interesting test to say the least, but I don't think it will work for the reason above.

**nested replaceable**

```html
// Use component
<my-component><template replace-part="abc">defines xyz</template></my-component>

// Component:
<template>
  <nested-comp>
    <template replace-part="xyz">
      <template replaceable part="abc"></template>
    </template>
  </nested-comp>
</template>
```

But you're nesting `replace-part` there, not `replaceable`.  Are you looking for nesting or for overriding defaults?

Could you make this into a more complete example and then add to that an example of what you would expect to be rendered? e.g. I'm not sure what "defines xyz" means to you there :)

**Comment by michaelw85** [comment]
@fkleuver I'm on vacation right now and do not have access to a laptop to write abd example but what I mean with defines xyz is that one replaceable template defines the content for a nested one. So the deepest component has xyz. But if we could not acces it directly within our consuming app the top level component would act as a proxy with it's own replaceable template.

Hope this makes any sense.

**Comment by artmasa** [comment]
@fkleuver I was referring to nesting custom elements. Many time you want to create base behavior and keep enhancing it with other features. En example of this could be a combo box component and then building a multi selection combo box. Instead of creating a completely new custom element I can leverage the behavior of the combo box for lookups. something that both will have in common is the template for the items in the list of possible selections and let the consumers define how the list items should look.

**combo-box.html**
```html
<template>
  <input type="text" value.bind="searchText" />
  <ul show.bind="showList">
    <li repeat.for="option of options">
      <template replaceable part="option-template">
        ${option.toString()}
      </template>
    </li>
  </ul>
</template>
```

**multi-select-combo.html**
```html
<template>
  <div repeat.for="item of selectedItems">
    <template replaceable part="item-template">${item.toString()}</template>
  </div>
  <combo-box selected.trigger="addItem()">
    <!-- feature request - replace part of combo-box but also make it replaceable -->
    <template replace-part="option-template" replaceable>
      ${option.toString()}
    </template>
  </combo-box>
</template>
```
**USAGE**
```html
<multi-select-combo>
  <template replace-part="item-template">
    <span class="list-item">${item.name}</span>
  </template>
  <template replace-part="option-template">
    <span><img src.bind="option.photo" />${option.name}</span>
  </template>
</multi-select-combo>
```


As you can see there is no need to define a `replaceable` template within a `replace-part` template in **`multi-select-combo.html`**

you can have:
```html
<template replace-part="option-template" replaceable></template>
```
instead of:
```html
<template replace-part="option-template">
  <template replaceable part="new-option-template"></template>
</template>
```

**Comment by fkleuver** [comment]
The various use cases mentioned in this issue (except for having `replace-part` and `replaceable` on the same element) are fixed with https://github.com/aurelia/aurelia/pull/499  to the best of my knowledge, so I'm closing this to tidy the issue list.

This can be reopened should anyone finds out that something isn't covered yet.

Thanks for all your input folks!
