### ISSUE TITLE
Development setup (manual browser testing) out of date

### ISSUE THREAD

**Issue by baerrach** [aurelia/aurelia#555]
https://github.com/aurelia/aurelia/tree/master/docs/engineering-notes#development-setup-manual-browser-testing

The command `cd packages && cd examples && cd jit-browserify && npm ci` will fail with the error `bash: cd: jit-browserify: No such file or directory`

**Comment by k-j-kleist** [comment]
Aside: If the Wiki Cheat Sheet https://github.com/aurelia/aurelia/wiki/Cheat-Sheet is out of date (which I'm far from sure of), maybe better remove it?

**Comment by fkleuver** [comment]
@baerrach That was actually a small typo, I corrected it. That said though, some of the stuff there is dated. Have been extremely busy with just getting stuff done, less so with trying to keep the docs accurate due to the ROI on that being pretty low atm.

@EisenbergEffect Since you are primarily working on documentation at the moment, could you maybe chime in here? What shall we do with some of those docs that went a bit out of date (but aren't completely useless either)?

@k-j-kleist The cheat sheet to the best of my knowledge provides working examples, just a few unnecessary `<any>` type casts which aren't needed anymore. Not sure about the routing part of that though.

@davismj do you have any time/interest in furthering work on that cheat sheet or should it be merged with @EisenbergEffect 's work?

@jwx could you glance over the router part of that cheat sheet and check if its ok, maybe make some additions?

**Comment by EisenbergEffect** [comment]
Funny, I don't even remember that Wiki being used....

In any case, I've started in work on the real documentation, which can be found in the `docs` folder. It's mostly just placeholder articles now, but about half a dozen of them in the getting started section have content. I'll make my next task to take the docs from the Wiki and port the relevant bits over to the official docs. Once that's done, I'm going to turn off the Wiki and update the readme file for this repo to point to the real docs.

**Comment by EisenbergEffect** [comment]
Wik has been removed and relevant bits are incorporated into the official docs. I have also update the user docs on getting set up for development, including steps on how to run tests in both chrome and node.

**Comment by EisenbergEffect** [comment]
Preliminary build and test docs are here: https://docs.aurelia.io/community-contribution/building-and-testing-aurelia
