### ISSUE TITLE
Building Aurelia 2 examples collection

### ISSUE THREAD

**Issue by adriatic** [aurelia/aurelia#567]
I am trying to document the build process for the collection of Aurelia 2 **[skeletons](https://github.com/aurelia/aurelia/tree/master/examples)**.

Here is the a question about `npm install` when using `scopes`:  what magic is being used to ensure that the components of Aurelia 2 build tree on my file system are correctly linked in `node_modules`

**Relevant details:**

### 1. created a2 build tree

My local disk layout is 

![image](https://user-images.githubusercontent.com/2712405/62659734-29adab80-b93a-11e9-8637-fbd594effeb4.png)

and I did run the usual steps
```
npm ci
npm run bootstrap
```

as well as 

```
npm run build 
```

As a consequence, I have the complete a2 build created at `C:\work\aurelia2\aurelia`.

### built the `jit-webpack-ts` example _outside_ of the a2 build tree

Running `npm install` in the (my private copy) of folder https://github.com/aurelia/aurelia/tree/master/examples/jit-webpack-ts, results with the creation of the folder `node_modules` - as shown below:

![image](https://user-images.githubusercontent.com/2712405/62659134-890abc00-b938-11e9-934f-6cd5332d2796.png)

The highlighted 'path to index.d.ts' is shown below:

![image](https://user-images.githubusercontent.com/2712405/62659284-f28aca80-b938-11e9-8ac3-f92e183aa1b5.png)

My question is: **where is the file `index.d.ts' (more precisely a2 distribution) coming from?**

**Comment by EisenbergEffect** [comment]
These are two very different scenarios. When you setup the entire repo, the bootstrap process is running Lerna commands under the hood. Lerna is a monorepo management tool. Some of the things it does are symlink local packages within the monorepo and hoist shared npm dependencies to the root of the repo. The skeletons are just normal packages. So, when you run npm install, it's actually installing Aurelia 2 from NPM directly. Inside the npm packages folder, there will be a subfolder for the `@aurelia` scope. Inside of that will be each of the Aurelia packages. Those packages each in turn have a dist folder, which is the product of the CI/CD build process. If you build the monorepo, you will see that dist folders get generated for each of the packages. That's what gets pushed to NPM during the automated publish.

**Comment by adriatic** [comment]
I understand the part (including the symlink and hoist actions). I also understand that the skeletons are not monorepos.

I do not understand your explanation 

> So, when you run npm install, it's actually installing Aurelia 2 from NPM directly

On my file system, the Aurelia 2 build tree and the samples tree are in two parallel folders, and `npm install` runs in the samples folder. Does `npm install` looks into `../aurelia' build tree`?

I hope that learning more about Huo's `makes` tool will get me the answer.

**Comment by EisenbergEffect** [comment]
The `npm install` that you run in the `examples` is not related to the local Aurelia monorepo build. As I mentioned, these are two completely different things. When you run `npm install` on an example, it is installing Aurelia 2 from npm. It does not use anything local, by design. We have developer builds of Aurelia 2 already published on npm (for over a year). We publish a build any time something is merged to master. The examples are setup to install those.

If you want to work on Aurelia itself, the Aurelia monorepo is what you want to work with. If you want to build an Aurelia app, you can use one of those example starters on its own. A better path would be to test out the new tooling we are working on: https://github.com/aurelia/new This will get a new project setup, with built-time conventions in place as well (which the "jit" samples do not have). I'll update the readme to include instructions related to makes for future visitors who just want to build an app.

**Comment by adriatic** [comment]
Thank you – things are perfectly clear now (I missed this “We have developer builds of Aurelia 2 already published on npm”). I do **not** have any needs to build Aurelia 2 binaries, although seeing how smooth and elegant is the build process was very comforting. It is obvious that the team took all experiences obtained in building Aurelia 1 and using monorepo added many benefits.

To clarify further: **I do want to build an Aurelia 2 app**, and being properly impressed with “makes” tool I will enthusiastically use it in as many contexts as possible.
