### ISSUE TITLE
`@processContent`

### ISSUE THREAD

**Issue by bigopon** [aurelia/aurelia#667]
# 💬 Discussion

In v1, custom element has `processContent` API to help user to prepare a custom element usage in a template before the compiler start processing it. It can also optionally compile the content, as the compilation process in v1 is processing and marking by id, unlike v2, processing and marking by order.

Up until now, the view compilation is split into two steps: [html -> symbols] then [symbols -> instructions]. This is difficult to support `processContent` API as it works with html, but [html ->symbols] step is not intuitive for end user as an API, so we should consider merging the two steps into one (compile from html -> instruction)

For now, `render` hook in custom element (and soon custom attribute) will allow us to support `processContent` usage, though through a much more ceremonial code.

This issue is a reminder that we should revisit this API once other items with higher priority are in place

## 🔦 Context

N/A

## 💻 Examples

N/A

@fkleuver @EisenbergEffect

**Comment by Sayan751** [comment]
The au1 signature is `static processContentFunction(compiler, resources: ViewResources, node: HTMLElement, instruction: BehaviorInstruction): boolean`. In au2 I think this should be simplified to `static processContentFunction(node: INode): boolean`. 


### Timing of the hook and regarding the return type
The `boolean` return value signified in au1 if the node needs to be enhanced or not. In Au2 it should mean if the node should be compiled or not. This justified below.

Let us say that `parent-ce` uses `my-ce` in its own definition template and `my-ce` defines the `processContent` hook. The current compilation pipeline (simplified) looks as follows.

1. Compile `parent-ce`
  1.1. TemplateBinder#bind
     1.1.1. loop over child nodes and create symbols
2. Compiler works on the symbols and turn those to instructions.

As per this current pipeline, 1.2. is the sweet spot to invoke the `processContent` hook. From this perspective, if a CE returns `false` from the `processContent` hook the `node` can be wrapped into a `PlainElementSymbol` to avoid further compilation of the content (hypothetically speaking; needs to verify with tests).

### Regarding the args
- The `node` is mutated.
- As the hooks in invoked during the template binding phase, the `compiler` is not yet available. That's why it can be omitted. There might be some interesting use case involving template compiler and `processContent`. However, IMO this can be ignored till we hear some real use-case which are infeasible otherwise.
- The `instruction` is also not available at this point.
- The `resources` can also be ditched, as with au2 all the CEs will be registered globally (I am assuming that to be the most frequent use-case). What might be an edge case is where the dev cooks up a new CE defn on the fly, and intends to use it only for this particular CE, for which the `processContent` hook is defined. For that we might need to pass the CE defn as the 2nd arg. However, IMO the mutation of the node is the most-frequent use cases. And from that perspective, this arg can also be avoided till we hear some real use-case which are infeasible otherwise.

**Comment by Sayan751** [comment]
During the course of development, the signature of the hook has been changed. Refer the [docs](https://docs.aurelia.io/app-basics/components-revisited#the-processcontent-hook) for details.
