### ISSUE TITLE
Clarify "Observing an expression on an object"

### ISSUE THREAD

**Issue by Alfhir** [aurelia/aurelia#726]
Hello,

[Observing an expression on an object](https://aurelia.io/docs/binding/binding-engine#observing-a-collection-mutation) is somewhat unclear to me. What is the difference between a chain and a path? How will this behave, when one of the properties is undefined?

**Comment by Alfhir** [comment]
https://aurelia.io/docs/binding/binding-engine#observing-a-collection-mutation

**Comment by fkleuver** [comment]
Hi, thanks for your feedback!

> What is the difference between a chain and a path?

In the sentence you're referring to, "a chain of property accesses (or a path)" could be rephrased as: "a chain of property accesses (in other words, a path)".

@EisenbergEffect We probably want to remove the "(or a path)" bit and instead write something like this: "a chain of property access (for example, `foo.bar.baz`)". It seems the terminology is not self-evident to everyone, understandably.

> How will this behave, when one of the properties is undefined?

It will return undefined. It will, by default, act as if there was a null-coalescing operator.

So: `foo.bar`, if `foo` is `undefined`, the evaluator will see that the object is undefined and just return `undefined`, instead of trying to access the property on it. Same goes for any level of nesting.

**Comment by Alfhir** [comment]
Sorry, im still confused about 
>  will notify you when any property within the path of expressionString has been changed

I created a [sandbox](https://codesandbox.io/s/github/Alfhir/au-expression-observer-sandbox) to support clarifying this.

I'd have expected, that 'any' means, that `.expressionObserver(this.obj, "foo.bar.baz")` would watch changes in `foo || bar || baz` or any possible combination of them. But it seems, it only observes changes in `baz`...which is what the property-observer does.

**Comment by Alfhir** [comment]
Got it. Property-Observer is used for observing "first-level" properties, Expression-Observer for nested properties.
