### ISSUE TITLE
Component Registration Doc is inaccurate

### ISSUE THREAD

**Issue by eiswind** [aurelia/aurelia#736]
https://github.com/aurelia/aurelia/blob/master/docs/user-docs/getting-started/components.md

says

```
Aurelia
  .register(
    NameTag // Here it is!
  )
  .app(App)
  .start();
```

Which does not compile because of register()'s type annotations.

Using

```
Aurelia.app(MyApp).register(NameTag).start();
```
does compile but does not work for me. If NameTag does have to implement IRegistry this could be documented.

**Comment by fkleuver** [comment]
> If NameTag does have to implement IRegistry this could be documented.

It doesn't. `CustomElement.define` or the `@customElement` decorator do this indirectly for you, so that's a little typing issue left over from earlier refactors that I'll address shortly.

The docs currently only address the convention-based approach for which the webpack loader is required. Is your project generated from the cli or did you create it by hand? Could you share the project via a repo?

**Comment by 3cp** [comment]
@fkleuver tsc does not know the "correct" type, because the editor does the type check with original code.

Even with the error in editor, the webpack build should work without issue, because tsc will see modified code at compile time.

I will double check my guessing. We might need to relax the type in Aurelia subclass defined in "aurelia" package.

**Comment by 3cp** [comment]
I just checked. This is annoying.

It is where conventions failed. It is from a TS project conventions.

When webpack starts bundling, it starts with `src/main.ts` where NameTag is checked. The tsc will check the type by reading `src/name-tag.ts` because main.ts asks for it.

But at this point of time, `src/name-tag.ts` is not modified because webpack has not started processing it. This is all tsc doing extra reading for type check.

I can think of two possible solutions, both are not very idea.
1. pass an option to tsc in webpack.config.js to turn off cross-file type checking. This requires we add another npm script "lint" to run real type check before "build".
2. relax the typing of Aurelia subclass defined in "aurelia" package.

**Comment by fkleuver** [comment]
@3cp as I said:

> that's a little typing issue left over from earlier refactors that I'll address shortly.

`.register` shouldn't have any restrictions on it, because things don't need to implement `IRegistry` to work in DI. Plain classes are jit registered as singletons, and resources are associated via metadata definitions which have a `register` method. So in both those valid cases (valid at build time and valid at runtime) they wouldn't conform to the api, meaning the api signature is wrong.

So the typing is an easy fix. What this is about is why his app does not work at runtime.

> Using

> Aurelia.app(MyApp).register(NameTag).start();

> does compile but does not work for me. If NameTag does have to implement IRegistry this could be documented.

But it's hard to tell what's wrong without the rest of the code.

**Comment by EisenbergEffect** [comment]
I was just going to chime and and say we probably just need to changes the types since DI can handle it regardless of whether it's a registry or not. But if it's not working at runtime, then there's some other very unexpected issue.

**Comment by EisenbergEffect** [comment]
@fkleuver Do you want to handle the type fixup?

**Comment by 3cp** [comment]
I see. @fkleuver recently refactored Aurelia instance method `public register(...params: any[]): this`, but the static register method in subclass in "aurelia" package need to follow that change.

There is something wrong why `Aurelia.app(MyApp).register(OtherOne).start();` doesn't render correctly. I can reproduce it.

**Comment by 3cp** [comment]
Update: Similarly rendering issue when using the underneath Aurelia.

This works.
```js
import {Aurelia} from '@aurelia/runtime';
import { JitHtmlBrowserConfiguration } from '@aurelia/jit-html-browser';
import { MyApp } from './my-app';
import { OtherOne } from './other-one';

const au = new Aurelia();
au
  .register(JitHtmlBrowserConfiguration)
  .register(OtherOne)
  .app({component: MyApp, host: document.querySelector('my-app')})
  .start();
```
This renders wrongly.
```js
const au = new Aurelia();
au
  .register(JitHtmlBrowserConfiguration)
  .app({component: MyApp, host: document.querySelector('my-app')})
  .register(OtherOne)
  .start();
```

Somehow, the register only works before `.app` calls.

**Comment by 3cp** [comment]
With the coming fix on typing, following code will work.

```js
import Aurelia from 'aurelia';

Aurelia
  .register(
    NameTag // Here it is!
  )
  .app(App)
  .start();
```

**Comment by fkleuver** [comment]
Ah yes now I remember. So `register` *must* come before `app`. There is nothing we can or will change about that, so we need to properly fix the types here to essentially disallow calling it the wrong way.

**Comment by fkleuver** [comment]
@eiswind @3cp @EisenbergEffect It's fixed in the latest `dev`

**Comment by EisenbergEffect** [comment]
Thanks @fkleuver !

**Comment by eiswind** [comment]
Thanks for the fix! Works like a charm now.
