### ISSUE TITLE
Provide an example for a component test

### ISSUE THREAD

**Issue by eiswind** [aurelia/aurelia#741]
# 🙋 Feature Request

Provide an example for a component test

## 🤔 Expected Behavior

Please add an example how to test a component.

## 😯 Current Behavior

I did not find any examples in the sources, please let me know if I#m blind...

## 🔦 Context

Testing components is one on the most important aspects.

## 💻 Examples

I tried something like 

```
        const ctx = TestContext.createHTMLTestContext();
        const container = ctx.container;
        const host = ctx.doc.createElement('div');
        ctx.doc.body.appendChild(host);
        const App = CustomElement.define({ name: 'app', template: `<template><say-hello></say-hello></template>` });

        const au = ctx.wnd['au'] = new Aurelia(container)
            .register(DebugConfiguration, RouterConfiguration, SayHello)
            .app({host: host, component: App});
        //
         await au.start().wait();
         assert.includes(host.innerHTML, 'say-hello', `host.innerHTML`);
         console.log(host.innerHTML)
         await au.stop().wait();
         ctx.doc.body.removeChild(host);
```
But this does not seem to render the say-hello component.

**Comment by fkleuver** [comment]
A few points on the side here:
- The `TestContext` is not proper public api yet. There's some initialization logic in `setup-browser.ts` / `setup-node.ts` in our own tests that isn't yet included. Aside from that, it's really just a means to allow for uniform testing between nodejs and the browser so you don't really need it.
- You also don't need to append your host to the body unless you're specifically testing routing and/or event delegation.
- Assigning `au` to the window is not something you normally want/need to do. There may still be some code like that in the repo but it should be removed.
- Top-level `<template>` element is not needed in your app template as long as your otherwise top-level element does not contain template controllers (`if`, `repeat`, etc) and as long as you don't need surrogate instructions (e.g. `class` to transfer to the host element)

When omitting the `TestContext`, thus manually setting everything up (the same would apply if you do not use the quick start api in production), you just need to register `JitHtmlBrowserConfiguration` which basically contains all the DI registrations for runtime, jit, etc.

Putting that all together, you get this:
```ts
const component = CustomElement.define({ name: 'app', template: '<say-hello></say-hello>' });

const host = document.createElement('div');

const au = new Aurelia()
  .register(JitHtmlBrowserConfiguration, DebugConfiguration, SayHello)
  .app({ host, component });

await au.start().wait();

assert.includes(host.innerHTML, 'say-hello', 'host.innerHTML');

await au.stop().wait();
```

Note that if you're using the webpack loader for conventions, you should also use that webpack loader in your testing setup.

**Comment by Vheissu** [comment]
How to test components have been documented in the official docs: https://docs.aurelia.io
