### ISSUE TITLE
Support for `@observable` inside of view-models

### ISSUE THREAD

**Issue by Vheissu** [aurelia/aurelia#785]
# 🙋 Feature Request

Add in support for the `@observable` functionality for observing changes to class variables inside of a view-model.

## 🤔 Expected Behavior

Users should be able to import the `@observable` decorator as per v1 and observe changes via change handlers on one or more properties inside of a class.

## 😯 Current Behavior

Not implemented.

**Comment by EisenbergEffect** [comment]
Dropping a note here as this may not strictly be necessary if we have support for getter/setter. For example, we should be able to support the VanillaJS equivalent..

```TypeScript
export class Person {
  private _firstName: string;

  get firstName() { return this._firstName; }
  set firstName(value: string) { this._firstName = value; this.firstNameChanged(); }

  firstNameChanged() {
    //...
  }
}
```

Ok, now that I write that out...I think we should still add `@observable` if only as an option for writing less code by hand. However, we should be able to support the vanilla version in au2 as well.

**Comment by arnederuwe** [comment]
I second the need for `@observable` 
Seeing the getter setter syntax reminds me of WPF in a bad way, people started writing business logic in their setters, even DB calls, resulting in business logic that was all over the place, full of race conditions and very hard to debug.
That's probably the biggest reason why we switched to Fody there (https://github.com/Fody/PropertyChanged), enforcing our developers to write 'dumb' properties otherwise binding would break :)
Come to think of it, perhaps you could do something similar with `@observable` and AOT? Generating getter/setters when you encounter the attribute ?

**Comment by fkleuver** [comment]
>  Generating getter/setters when you encounter the attribute ?

That's exactly what already happens at runtime. `@bindable` uses `defineProperty` to replace the field with a getter/setter pair. Indeed, AOT can do that ahead of time and make the thing a bit more speedy, but fundamentally the mechanism stays the same :)
