### ISSUE TITLE
kernel: jitRegister injects intrinsic types

### ISSUE THREAD

**Issue by xenoterracide** [aurelia/aurelia#840]
https://www.typescriptlang.org/docs/handbook/basic-types.html and other types like Array, Promise, Function, are automatically injected, regardless of the fact that this could have disastrous results in production, especially in cases where the values are in theory determined at runtime.

In my humble opinion such base types without a valid registration, should throw an exception.

**Comment by fkleuver** [comment]
Thanks for creating the issue. I agree that some facility to detect this is appropriate. A config flag to disable jitRegister should probably be added to the DI api regardless.

Whether or not to *always* throw on intrinsics is another question.

For reference, there are 33 intrinsic types (and an additional 5 lowercase aliases that resolve to their capitalized counterparts) to which this would apply (as per the ES spec: http://www.ecma-international.org/ecma-262/#sec-well-known-intrinsic-objects)
- `Array`
- `ArrayBuffer`
- `Boolean` (also represents `boolean`)
- `DataView`
- `Date`
- `Error`
- `EvalError`
- `Float32Array`
- `Float64Array`
- `Function`
- `Int8Array`
- `Int16Array`
- `Int32Array`
- `Map`
- `Number` (also represents `number`)
- `Object` (also represents `object`)
- `Promise`
- `RangeError`
- `ReferenceError`
- `RegExp`
- `Set`
- `SharedArrayBuffer`
- `String` (also represents `string`)
- `Symbol` (also represents `symbol`)
- `SyntaxError`
- `TypeError`
- `Uint8Array`
- `Uint8ClampedArray`
- `Uint16Array`
- `Uint32Array`
- `URIError`
- `WeakMap`
- `WeakSet`

Putting all these intrinsics into an array and using an `includes` check would work in principle, but might cause issues in unintentional cross-realm scenarios such as those sometimes caused by jest, or even intentional when sharing a container across same-origin iframes.

Two potentially robust alternatives would be:
1) Check the `name` property and match it against these values
2) Use `.toString()` on the constructor and check whether it contains `[native code]`

**Comment by xenoterracide** [comment]
I'd be fine with either approach, though 1. actually sounds more robust as I suspect there'll be new types that are first serviced by polyfills and overriding names sounds bad... I supposed you could actually check both.

**Comment by fkleuver** [comment]
I think 1. is probably preferable as well yeah. For performance reasons as well. Feel free to work on it if you want. Thanks :)

**Comment by xenoterracide** [comment]
So what I've learned so far, `jitRegister` never hits for the string, in fact it looks like for all of these

```
      class Foo {
        public constructor(private readonly test: string) {
        }
      }
```
the DI system doesn't think their are any dependencies at all... it's just calling `new Foo()`

**Comment by xenoterracide** [comment]
shouldn't this test return something in the `actual`, I'm getting `undefined`

```ts
    it('constructor string', function () {
      class Foo {
        public constructor(public readonly test: string) {}
      }

      const actual = Metadata.getOwn('design:paramtypes', Foo);
      assert.strictEqual(actual, []);
    });
```

**Comment by fkleuver** [comment]
You do need to put a decorator on the class in order for metadata to be emitted. Any decorator will do:
```ts
  function deco() {}

    it('constructor string', function () {
      @deco
      class Foo {
        public constructor(public readonly test: string) {}
      }

      const actual = Metadata.getOwn('design:paramtypes', Foo);
      assert.strictEqual(actual, []);
    });
```
