### ISSUE TITLE
Aurelia plugin doesn't look at package.json

### ISSUE THREAD

**Issue by brandonseydel** [aurelia/aurelia#886]
# 🐛 Bug Report

The plugin that modifies the source code on gen doesn't look into package.json to determine if you are using aurelia or the individual packages.  This breaks things when generating code under the aurelia package.

## 🤔 Expected Behavior

When generating customElement is imported from the correctly references package from package.json

aurelia if exists else @aurelia/runtime

## 😯 Current Behavior

customElement is always exported from @aurelia/runtime

## 💁 Possible Solution

scan package.json

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Aurelia          |
| Language         |
| Browser          |
| Bundler          |
| Operating System |
| NPM/Node/Yarn    |

**Comment by 3cp** [comment]
I think conventions doesn't suppose to scan to that extend, it feels doing too much. Be ware that not just `package.json`, there are also `package.yml` and `package.json5` that some people use.

I understand this is a problem for yarn2 which denies deep dep in strict mode. We need more opinions on this yarn2 compatibility issue.

> customElement is always exported from @aurelia/runtime

This is designed to support both au2 app and (future skeleton) au2 plugin project. Because in plugin project, we definitely don't want to put "aurelia" in dependencies.
Currently conventions only read current file (feed by bundler) and scan just the paired file (either html or css).

Instead of scanning `package.json`, we could add an user option like `importFromAurelia: false` which is only needed to turn on for au2 app (not plugin) using yarn2.

**Comment by 3cp** [comment]
FYI yarn2 is going to use loose mode as default in probably v1.1, so this should not be an issue in future.

**Comment by brandonseydel** [comment]
this just doesn't work anywhere.

**Comment by brandonseydel** [comment]
![image](https://user-images.githubusercontent.com/5033585/82519688-dcc14d00-9ae7-11ea-9fc6-31e956490acd.png)

**Comment by brandonseydel** [comment]
That happens if it tries to use the @aurelia package.  That is why i have to include customElement off off aurelia so it doesn't dip and then uses the correct one.

**Comment by 3cp** [comment]
Probably a typing regression in latest code (aurelia, not conventions) instead of importing issue.

**Comment by brandonseydel** [comment]
![image](https://user-images.githubusercontent.com/5033585/82519896-6ec95580-9ae8-11ea-996c-f905cf3fea05.png) breaks with error

![image](https://user-images.githubusercontent.com/5033585/82519916-7be64480-9ae8-11ea-9982-e94dc41ec643.png) works fine

customElement is imported differently causing it to break.

**Comment by fkleuver** [comment]
Can this be reproduced? It should work regardless. Package.json scanning would be a band aid. I want to find out why this is breaking and fix it at the root. It feels like a semver issue like multiple version dep trees or something

**Comment by 3cp** [comment]
Is that only break in your vscode check? The app can still build and run from command line?

I am testing a newly created default webpack+ts app, I got no problem running the app. And my vscode didn't complain about customElement imported from "aurelia".
 
![Screen Shot 2020-05-21 at 1 32 57 pm](https://user-images.githubusercontent.com/1188806/82520492-9d3a4580-9b67-11ea-8063-ee044c5bb816.png)

**Comment by 3cp** [comment]
Oh, I guess I got what you mean.

You imported customElement from "aurelia" but didn't use it.
Then conventions tries to double import the same customElement from "@aurelia/runtime" which breaks your code.

**Comment by brandonseydel** [comment]
it is happening in 
aurelia-ionic project
storybook main repo
aurelia-content-loader

**Comment by 3cp** [comment]
Please provide a mini repo if you can reproduce it. It does sound like a version issue. You can try to find out duplicated versions.
```
npm ls @aurelia/runtime
npm ls aurelia
```

I cannot reproduce the issue. Following code worked in my repo

```ts
import {customElement} from 'aurelia';

export class MyApp {
  public message = 'Hello World!';
}
```

**Comment by fkleuver** [comment]
The thing is though, I already added guard code in the metadata package at module scope that detects this situation based on whether `Reflect` is already patched or not. Since you're not getting that error, if it is indeed version-related, then it has to be a version of at least 1-2 weeks ago from before I added that guard code

**Comment by 3cp** [comment]
Try fresh install... and flow away caches on your CI...

**Comment by brandonseydel** [comment]
@fkleuver @3cp looks like after the 5/20 version it works correctly.  The versions were a couple weeks old.
