### ISSUE TITLE
aurelia/metadata conflicts with reflect-metadata which is required by typeorm

### ISSUE THREAD

**Issue by xenoterracide** [aurelia/aurelia#902]
```
    Conflicting reflect.metadata polyfill found. If you have 'reflect-metadata' or any other reflect polyfill imported, please remove it, if not (or if you must use a specific polyfill) please file an issue
at https://github.com/aurelia/aurelia/issues so that we can look into compatibility options for this scenario.

      at Object.applyMetadataPolyfill (node_modules/@aurelia/metadata/src/index.ts:1032:11)
      at node_modules/@aurelia/kernel/src/di.ts:3:1
      at node_modules/@aurelia/kernel/dist/umd/di.js:3:17
      at Object.<anonymous> (node_modules/@aurelia/kernel/dist/umd/di.js:9:3)
      at node_modules/@aurelia/kernel/src/index.ts:1:1
      at node_modules/@aurelia/kernel/dist/umd/index.js:3:17
````

**Comment by fkleuver** [comment]
Is there a specific reason why `reflect-metadata` must be used? Have you tried removing it?

**Comment by xenoterracide** [comment]
we removed it from our direct dependencies, but it's pulled in as a transient dependency

**Comment by fkleuver** [comment]
>  but i'd suspect they use the reflect-metadata APIs

That's fine, it's just a polyfill. `@aurelia/metadata` provides the same polyfill and is therefore able to replace `reflect-metadata`. The reason for this error is because our polyfill addresses two minor issues that surfaced in `reflect-metadata` and we need those fixes in order for things to work.
I have a workaround for this in the making where our polyfill can be manually invoked to force-overwrites any existing one, I'll try to get it in this week.

**Comment by xenoterracide** [comment]
any chance you could enumerate those minor issues, just so I understand them in case it causes any problems with typeorm? also not entirely certain how they conflict since they should be being used on different classes? but maybe not...?

**Comment by fkleuver** [comment]
> any chance you could enumerate those minor issues, just so I understand them in case it causes any problems with typeorm?

`tslib`'s static property polyfill is slightly more permissive, so some things that work with just `tslib` will throw when `reflect-metadata` is installed. I only realized this several iterations later when I forgot the specifics, but I'll look into it again and make a note about it in our docs before we go RC.

TypeORM has been around for a long time, I don't imagine you'll run into any `reflect-metadata` related issues that they haven't either already worked around or have existing issues for that can easily be found with a search.

We probably just happen to use a bigger (less common) portion of the `Reflect.metadata` spec's api surface that the much more battle-tested `tslib` accounts for but the less commonly used `reflect-metadata` does not.

> also not entirely certain how they conflict since they should be being used on different classes? but maybe not...?

You need to understand the concept of [polyfills](https://en.wikipedia.org/wiki/Polyfill_(programming)).

The "accepted" way of doing polyfills is: only apply it if it doesn't already exist in the environment.
In this case, that works against us because there is a problematic implementation that happens to be usually applied first.

If we let that go, then there will be failures in some of our APIs because of `reflect-metadata` and they surface in the weirdest places, making them pretty hard to troubleshoot if you don't know what you're looking for. Hence the early error which makes it much clearer what is the problem and how to solve it.

We could overwrite any existing polyfill (and log a warning and then also prevent future overwrites), which is probably the next move, I just want to first get an idea of whether there are any situations where we should *not* be overwriting existing polyfills. So far, though, that doesn't seem to be the case as it's always `reflect-metadata` and we already know we can safely replace that.

**Comment by xenoterracide** [comment]
Thanks for the information, polyfills, monkey patching. I more or less get it, just wasn't entirely certain (probably due to java not really supporting these) how you'd overwrite reflect-metadata when they're going to be using there imports.

note: also ok with this error being thrown if you can disable it, or maybe disable it conditionally on a certain library, so people are still reporting. I'll leave that up to you though.

**Comment by fkleuver** [comment]
Polyfills only exist when the same API can be implemented by multiple environments/products that might not all be in feature parity.
It helps that Java is only released by Oracle, and not by 4+ different vendors competing for market share :)

> how you'd overwrite reflect-metadata when they're going to be using their imports, and your published API is different.

No, not overwriting `reflect-metadata`. Rather, there is a global `Reflect` object that we both try to add properties to.
Look at it in your browser console (this is an ES spec thing so it exists both in node and in the browser). It doesn't have methods like `defineMetadata`. That's what these polyfills add.

> note: also ok with this error being thrown if you can disable it, or maybe disable it conditionally on a certain library, so people are still reporting. I'll leave that up to you though.

Plan is to expose some options yeah.

**Comment by fkleuver** [comment]
Fixed by https://github.com/aurelia/aurelia/pull/907

You can override `reflect-metadata` by putting this at the top of your entry file:
```ts
import { applyMetadataPolyfill } from '@aurelia/metadata';
applyMetadataPolyfill(Reflect, false, true, false, false);
```

This should be a safe thing to do, as our implementation is more permissive than `reflect-metadata` and also has more tests verifying those situations.
