### ISSUE TITLE
Confirmation before closing of tab

### ISSUE THREAD

**Issue by Erythros** [aurelia/aurelia#911]
While this is not directly an issue or a feature request, I'm wondering if anyone has stumbled upon the same question.

I'm looking for a way to implement a confirmation dialog whenever the browser's tab is closed if the forms have any kind of user entered data.

`canDeactivate` is pretty helpful and I managed to implement a similar solution for when the user navigates away from the current page.

However, haven't figured out a proper way to solve the same problem for when the browser tab is closed.

Any hints are much appreciated!

**Comment by fkleuver** [comment]
You can use the `window.onbeforeunload` event for that (that's not specific to Aurelia btw).
@jwx just dropping a note here for something to potentially look into post-alpha. Might be nice to add a built-in router config option to have the router respond to that event with its lifecycles?

**Comment by Erythros** [comment]
> You can use the `window.onbeforeunload` event for that (that's not specific to Aurelia btw).

Is there a difference between using, as you suggested, `onbeforeunload` like

```ts
public async activate(): Promise<void> {
    this.refreshClicked = (e) => {
            const confirmation = "Are you sure you want to exit?";
            e.returnValue = confirmation;

            return confirmation;
        };
}

public attached(): void {
        window.addEventListener("beforeunload", this.refreshClicked);
    }
```
OR just using
```ts
public canDeactivate(): boolean {
        return confirm("Are you sure you want to exit?");
    }
```
From some quick testing, it seems like the same goal is achieved either way. Unless I miss something.

**Comment by Nness** [comment]
* `beforeunload` could mean route change outside of single page application's routing. e.g. refresh clicked, navigate to another website etc.
* canDeactivate is internal framework event, it can translate to route related or component destroy event based on the framework you are using.

In theory you should subscribe to both, since it has same meaning but from different source. Framework normally won't care about `beforeunload` event, since it is not their responsibility. If they do, then question will arise. What does `canDeactivate` mean? Is it `beforeunload` or app event? Then we need state from `canDeactivate` to describe.
