### ISSUE TITLE
Allow scoped scoped registration for interfaces cachedCallback and singleton

### ISSUE THREAD

**Issue by xenoterracide** [aurelia/aurelia#914]
we introduced `@singleton({scoped:true})` which means it would be registered with the requesting container. We need the same feature for interfaces. Proposed

```
DI.createInterface( b => b.cachedCallback(() => new Connection, { scoped: true });
```

**Comment by bigopon** [comment]
for `cachedCallback` I dont think we can have `scoped` behavior since there's no control from the aurelia side of where the key will be first registered. Though registration can be fully controlled from application side, like this:
```ts
const MyInterface = DI.createInterface(b => b.cachedCallback((handler, requestor) => {
  const instance = new Connection;
  requestor.register(Registration.instance(MyInterface, instance));
  return instance;
}));
```
I'll close this for now, but pls feel free to reopen if you don't see this as an appropriate level of control from application side.
