### ISSUE TITLE
[Question]: Use Vue UI parts from old project in a new Aurelia one? 

### ISSUE THREAD

**Issue by sturlath** [aurelia/aurelia#947]
I was just reading the [vnext 2019 fall update](http://aurelia.io/blog/2019/10/31/aurelia-vnext-2019-fall-update) and I noticed this comment

> As an example, the template syntax for Angular, Knockout, Vue, etc. can all easily be implemented in Aurelia 2 by simply registering a few classes in the dependency injection container.

**What does that mean**?

Let's say I have a Vue solution right now... can I rip out the UI part (in Vue)  and add them to Aurelia and it works?

Could you then also use plugins and components from the Vue community in your Aurelia solution?

Sorry if I have misunderstood this all, I have not touched javascript (or framework) in a long time but now I need to start a new project and would like some information on Aurelia.

**Comment by fkleuver** [comment]
> Let's say I have a Vue solution right now... can I rip out the UI part (in Vue) and add them to Aurelia and it works?

To the extent that the same directives, bindings etc are implemented in Aurelia, yes, and we do intend to have at least feature parity in terms of OOTB directives / bindings with other major frameworks.

This applies only to the UI part (so the html templates). Of course we can't guarantee a 100% change-free emulation in all situations when there are API differences. We haven't done a full inventory / analysis yet but we will work on some proper examples and make them available post-alpha.

> Could you then also use plugins and components from the Vue community in your Aurelia solution?

We don't know that yet, but we're certainly going to try.

There are 2 different situations here:
### Running one framework inside of another

We designed Aurelia 2 so that you can run multiple instances within the same realm (window), as well as run Aurelia inside of other frameworks. Any framework that has a "script tag" distribution (which Vue does) should be able to at least run inside another framework. Not sure if Vue and others have multi-instance capabilities. We use DI to accomplish that and avoid relying on any kind of global / module-scoped state.

In short, this means you might be able to run a single Vue component inside an Aurelia app by simply booting up a Vue instance to render it, but that's probably not what you're after. I'm just mentioning it to paint the full picture.

### Running *components* of one framework inside of another.

ionic is a good example of components that are distributed in a way that any framework can use them.

The key thing here is that components are self-contained and their instantiation is handled natively by the browser via the web components api. They might import some libraries / part of framework, but they don't require that framework to do the bootstrapping, (or if they do, then that framework must be able to run multiple instances in the same realm (window) and not require any special tooling - we have this capability as explained in the previous point).

We will offer a means to distribute components in this manner as well (meaning you can use Aurelia components in any other framework), but of course we cannot speak for our competitors.

If Vue doesn't have this capability then it would require more than just emulating their syntax. Something needs to call the appropriate component APIs and call them in the right order, pass the right state, etc, and probably access internals as well. If even possible, that would be too much of a moving target and so we're not going to be doing that.
But if someone in the community wanted to have a crack at it, we would be more than happy to help accommodate for it by adding any missing extensibility points.
